export interface Location {
  slug: string;
  name: string;
  postcode?: string;
  borough?: string;
  description: string;
  // Optional genuinely-local copy shown at the top of the area page. Fill this in
  // for priority areas so those pages have unique content rather than a template.
  localIntro?: string;
  // Optional deeper local copy for priority areas: what we typically get called out
  // for here, and the practical logistics of reaching you. Rendered only when present,
  // so areas without them fall back to the existing template unchanged.
  localRepairs?: string;
  localLogistics?: string;
}

export const locations: Location[] = [
  // Surrey Belt / South West London
  { slug: 'new-malden', name: 'New Malden', postcode: 'KT3', borough: 'Kingston upon Thames', description: 'New Malden and Kingston border area', localIntro: 'New Malden is home base for us, so response times here are the fastest we offer anywhere in London — we can often be at your door in New Malden, Motspur Park or Old Malden within the hour. We regularly help the area\'s many home workers and small businesses along Coombe Road and the High Street with MacBook and laptop repairs without them ever leaving their desk. Being local matters more than it sounds: we know which streets around Beverley Park are a nightmare to park on, we know the difference between a KT3 address that\'s really Motspur Park and one that\'s really Old Malden, and we can usually slot a New Malden job into the same day even when the diary is full, because there\'s no travel time to absorb. New Malden has one of the largest Korean communities in Europe, and a good number of our call-outs come from the independent businesses along the High Street and Burlington Road — restaurants, salons and small offices where a dead till PC or a laptop that won\'t boot stops the day cold. We treat those as urgent, because they are.', localRepairs: 'The New Malden housing mix — a lot of 1930s semis and converted flats — means we see plenty of machines that have been in the same household for years: iMacs that have slowed to a crawl, MacBooks on their second or third battery, and family PCs clogged with a decade of software. Storage upgrades and clean reinstalls are probably our most common New Malden job. The other half is the small-business side: along the High Street we\'re regularly asked to look at a laptop that\'s the only machine in the building, which is why we carry common parts with us and try to finish on-site rather than taking anything away. We also get a steady run of student and school machines from families near Coombe Boys\' and Coombe Girls\' — usually cracked screens, snapped hinges and liquid damage, which is exactly what you\'d expect from a laptop that lives in a rucksack.', localLogistics: 'We\'re based in New Malden, so there\'s no callout charge and realistically no travel delay — if you call in the morning we can usually be with you before lunch. Parking is generally fine on the residential roads; if you\'re on the High Street or near the station we\'ll ask you where\'s best rather than circling. Evenings and weekends are no extra charge here, same as everywhere else we cover, and most repairs are done in front of you at the kitchen table or your desk.' },
  { slug: 'kingston-upon-thames', name: 'Kingston upon Thames', postcode: 'KT1', borough: 'Kingston upon Thames', description: 'Kingston town centre and surrounding areas', localIntro: 'We cover all of Kingston upon Thames — from the riverside offices and the Bentall Centre area to the residential streets around Norbiton and Kingston Hill. With Kingston University nearby we see a lot of student MacBooks with cracked screens and failing batteries, and we can usually visit the same day rather than making you carry the machine into town. Kingston is the one place on our patch where people most often assume they have to queue somewhere. You don\'t — we\'re five minutes up the road in New Malden, and coming to your flat in Norbiton or your office near the Rose Theatre costs you nothing extra and saves you an afternoon. The town splits into two very different jobs for us: the town centre — offices, retail units and the flats above them, where the machine is usually work-critical and needs fixing today — and the residential belt up Kingston Hill and out toward Coombe, which is more family machines, more iMacs, more "it\'s been getting slower for a year and now it won\'t start".', localRepairs: 'Student laptops dominate around term time. Cracked screens are the single most common Kingston call-out we get — a MacBook Air that\'s been closed on a pen, or a laptop that\'s gone off a desk in halls — and we carry the common Air and Pro screens, so most of those are done on-site in under an hour. Battery swaps are the close second: a three or four year old MacBook that won\'t hold charge through a lecture or a working day is a straightforward job we can almost always finish in front of you. For the town-centre businesses it\'s more varied — dead PCs, failing drives, Wi-Fi that won\'t reach the back office, and the occasional liquid-damage emergency. Data recovery comes up more here than in most of our areas — usually a dissertation or a set of accounts on a drive that\'s stopped mounting.', localLogistics: 'Kingston is a ten-minute run from our New Malden base, so same-day is realistic if you call before 2pm, and often sooner. We\'ll come to halls, a flat, an office or a café — wherever the machine is. Parking in central Kingston is genuinely difficult and the one-way system doesn\'t help, so for town-centre jobs we\'ll agree the address and access with you when you book rather than guessing. It never costs you anything extra; it just helps us arrive when we said we would.' },
  { slug: 'wimbledon', name: 'Wimbledon', postcode: 'SW19', borough: 'Merton', description: 'Wimbledon and South Wimbledon', localIntro: 'From Wimbledon Village down to South Wimbledon and Wimbledon Park, we come to your home or office rather than asking you to queue at a shop. We look after a lot of the area\'s professionals working from home around the Common, and can handle everything from a slow iMac to a liquid-damaged MacBook on-site. Wimbledon is one of our strongest work-from-home patches: a large share of our SW19 call-outs are people whose laptop is their job — consultants, designers, people running a business from a spare room — and for them a machine that\'s down for three days in a shop isn\'t an inconvenience, it\'s lost income. That\'s the whole reason we work the way we do. The area\'s split matters too: the Village is largely period houses and older, well-looked-after Macs, while South Wimbledon and the Broadway are flats, shared houses and a younger mix of machines. During the Championships fortnight the roads around the All England Club are chaos, and we plan around it so a booked visit still lands when we said.', localRepairs: 'The work-from-home mix means a lot of what we do in Wimbledon is keeping otherwise-healthy machines alive: battery replacements, SSD upgrades on Macs that have got sluggish, and clearing out the software mess that builds up on a machine nobody\'s had time to maintain. Liquid damage is a recurring one — a coffee into a MacBook keyboard at a home desk is one of the most common emergency calls we get here, and if you can get to us fast the odds are much better than most people assume, so it\'s always worth the call before you write the machine off. We also see a fair number of external drives and Time Machine backups that have quietly stopped working, usually discovered at the worst possible moment; checking that your backup actually runs is free advice we give on every visit.', localLogistics: 'Wimbledon is a short hop from New Malden and we\'re there most days, so same-day visits booked before 2pm are usually straightforward. Parking around the Village and the Common is permit-heavy and tight, so we\'ll ask about access when you book — it\'s not a problem, we just plan for it. Evening and weekend slots are no extra charge, which suits the people here who can\'t stop work mid-afternoon to meet an engineer.' },
  { slug: 'raynes-park', name: 'Raynes Park', postcode: 'SW20', borough: 'Merton', description: 'Raynes Park and West Barnes', localIntro: 'Raynes Park\'s mix of Victorian terraces and new-build flats around the railway station means we see everything from vintage iMacs to brand-new gaming laptops. We cover Raynes Park and neighbouring West Barnes on the same visit, so a call before 2pm usually means same-day help at your door. Raynes Park sits right between our New Malden base and Wimbledon, which makes it one of the easiest areas for us to reach — we\'re often passing through anyway — so we can usually be more flexible about timing here than in areas further out. It\'s a quietly busy patch: the terraces off Coombe Lane and Bushey Road are largely families and long-term residents, and the newer flats near the station skew younger and more remote-working. The result is a genuinely mixed bag of machines: we\'ll do a gaming PC that won\'t POST in the morning and a fifteen-year-old iMac somebody can\'t bear to part with in the afternoon.', localRepairs: 'Family machines are the backbone of the work here — laptops that have slowed down, run out of storage, or been dropped by somebody\'s teenager. Screens, hinges and keyboards, mostly, and a lot of straightforward speed-ups that don\'t need new hardware at all. Gaming PCs come up more in Raynes Park than you\'d expect: overheating, fans screaming, random shutdowns under load — usually dust, thermal paste or a power supply on the way out, and almost always fixable on-site. The older iMacs are a soft spot of ours — a 2013 or 2014 machine with an SSD and a clean install genuinely feels new again, at a fraction of the cost of replacing it, and we\'ll always tell you when that\'s the better call.', localLogistics: 'We\'re a few minutes away and frequently in the area, so Raynes Park and West Barnes are among the quickest visits we do — same-day is usually easy, and we can often be more flexible on timing than elsewhere. Parking is generally fine on the residential streets, though the roads immediately around the station get busy at commuter hours. No callout charge, and evenings and weekends are the same price as any other slot.' },
  { slug: 'morden', name: 'Morden', postcode: 'SM4', borough: 'Merton', description: 'Morden and surrounding areas', localIntro: 'As the southern terminus of the Northern line, Morden is home to a lot of commuters who rely on a working laptop the moment they\'re back from London. We\'re regularly out around Morden Hall Park and the town centre, fixing everything from slow PCs to cracked MacBook screens without anyone needing to queue at a shop.' },
  { slug: 'sutton', name: 'Sutton', postcode: 'SM1', borough: 'Sutton', description: 'Sutton town centre', localIntro: 'Sutton\'s busy high street and office blocks around the town centre keep us on our toes — a lot of our call-outs here are small businesses that can\'t afford a laptop being out of action for a week. We visit homes and workplaces across Sutton the same day where we can, with no callout charge either way.' },
  { slug: 'cheam', name: 'Cheam', postcode: 'SM3', borough: 'Sutton', description: 'Cheam Village and North Cheam', localIntro: 'Cheam Village and North Cheam are among the quieter, more residential calls we get — often families whose children\'s laptops have taken a knock, or a MacBook that\'s simply slowed down with age. We come to your door in Cheam just as readily as anywhere else in the Sutton borough, with the same no callout charge and 90-day warranty. It\'s a settled, family-heavy area, and that shapes the machines we see: computers that have been in the household for years and are quietly overdue a battery, a bigger drive, or a clear-out. A lot of what we do here is the unglamorous but genuinely useful stuff — making a tired machine usable again rather than writing it off — and being straight with you about when a repair is worth it and when it isn\'t. We cover Cheam Village, North Cheam and the streets toward Worcester Park on the same trip, and most repairs are done in front of you at home.', localRepairs: 'Family and student machines dominate the work in Cheam. Cracked screens and snapped hinges on laptops that live in a school bag, batteries that no longer last a day, and MacBooks that have filled up and slowed down are the everyday jobs — and we carry the common parts so most are finished on-site in an hour. The older desktops and iMacs are the other regular. A machine that feels hopelessly slow is often just short of an SSD and a clean install, and that one upgrade brings it back for a fraction of a replacement. We\'ll always tell you when that\'s the better call. Liquid spills and won\'t-turn-on faults come up too, and as always the quicker we see those, the more we can usually recover.', localLogistics: 'Cheam is a short run from our New Malden base, so same-day visits booked before 2pm are usually easy to arrange. Parking is generally straightforward on the residential streets around the Village, so reaching your door is rarely an issue. There\'s no callout charge anywhere in the area, evenings and weekends cost the same as a weekday slot, and every repair carries our 90-day parts-and-labour warranty — with nothing to pay at all if we can\'t fix the fault.' },
  { slug: 'epsom', name: 'Epsom', postcode: 'KT18', borough: 'Epsom and Ewell', description: 'Epsom and Ewell area', localIntro: 'Best known for the Derby at Epsom Downs, the town itself is full of home workers and small offices who need a Mac or laptop fixed without losing a working day. We cover all of Epsom and the surrounding villages, and can usually get to you the same day if you call before 2pm. Epsom spreads out more than most towns on our list — the town centre and station area, then the residential streets climbing toward the Downs, then the villages beyond. We treat it as one patch and come to wherever the machine is, whether that\'s a home office near the racecourse or a small business off the High Street. Most faults we diagnose and fix in front of you, with the price agreed before we touch anything. We cover Epsom, Ewell and the neighbouring villages on the same basis, with no callout charge and the same 90-day warranty on every repair.', localRepairs: 'The home-office and small-business mix in Epsom means a lot of the work is keeping working machines working: battery swaps, storage and memory upgrades, and clean-ups on Macs and PCs that have slowed under years of use. We carry common parts and aim to finish in a single visit rather than leaving a desk empty for a week. Cracked screens and worn batteries on family and student MacBooks are steady too, and where a machine just feels tired an SSD and a fresh install usually transform it far more cheaply than a replacement. For the small businesses, it\'s more varied — a till or office PC that won\'t boot, a drive on its way out, or Wi-Fi that won\'t reach the back of a unit — and those we treat as priority, because a dead computer stalls the whole day.', localLogistics: 'Epsom is a slightly longer run than our closest areas but firmly within our range, with no callout charge, and same-day is usually workable if you call before 2pm. The town is spread out, so for the villages and the streets up toward the Downs we\'ll confirm the address and access with you at booking — it helps us arrive when we said we would. Parking is generally easier here than in the busier town centres we cover. Evenings and weekends are no extra charge.' },
  { slug: 'ewell', name: 'Ewell', postcode: 'KT17', borough: 'Epsom and Ewell', description: 'Ewell and Nonsuch area', localIntro: 'Ewell Village, with Bourne Hall and Nonsuch Park close by, is one of the quieter corners of our patch — but we\'re out here regularly, usually for local families whose MacBook has slowed down or a laptop that\'s taken a knock. We come to your door in Ewell rather than asking you to drive a broken machine into Epsom or Kingston, and there\'s no callout charge either way. It\'s a settled, residential area, and that shows in the machines we see: computers that have been in the same household for years and are quietly on their second battery or running low on space. A lot of what we do here isn\'t dramatic — it\'s bringing a tired but perfectly good Mac or laptop back to life rather than replacing it, and telling you honestly when that\'s the smarter spend. We cover Ewell Village, West Ewell and the streets toward Stoneleigh on the same basis, usually on the same trip, and most repairs are done in front of you at the kitchen table.', localRepairs: 'Family machines are the backbone of the work in Ewell — laptops that have got sluggish, run out of storage, or been dropped by somebody\'s teenager. Battery replacements and cracked-screen jobs on MacBooks come up most, and we carry the common Air and Pro parts so a lot of those are finished on-site in under an hour. The other steady job is the speed-up: an older iMac or laptop that feels past it but only really needs an SSD and a clean install to work like new again. It\'s the cheapest thing you can do to a slow computer, and we\'d rather fit one than sell you a repair you don\'t need. We also get the occasional liquid spill and won\'t-turn-on emergency — and with those, the sooner you call, the more we can usually save.', localLogistics: 'Ewell is a short run from our New Malden base, so same-day is usually straightforward if you call before 2pm. Parking is generally easy on the residential streets around the Village, so getting to your door is rarely a problem. Evenings and weekends are no extra charge, same as every other slot we offer, and every repair carries the same 90-day parts-and-labour warranty. No callout fee, and nothing to pay at all if we can\'t fix the fault.' },
  { slug: 'tolworth', name: 'Tolworth', postcode: 'KT6', borough: 'Kingston upon Thames', description: 'Tolworth and Surbiton', localIntro: 'Tolworth\'s mix of offices along the A3 and residential streets nearby means our call-outs here range from small-business PCs to home laptops that won\'t start. We treat it as part of our core Kingston-area patch, so response times here are among the fastest we offer anywhere. Being this close to base changes how we can work Tolworth: there\'s almost no travel time to absorb, so we can usually slot a job in the same day even when the diary is busy, and we\'re flexible on timing in a way we can\'t always be further out. The area really is two jobs in one — the business side along the A3 and the Broadway, where a dead machine stops the working day and needs fixing now, and the residential streets behind it, where it\'s more family laptops and Macs that have slowed with age. We cover Tolworth, Berrylands and neighbouring Surbiton on the same trip where it makes sense, with no callout charge.', localRepairs: 'For Tolworth\'s offices and small businesses, the common jobs are dead or failing PCs, drives on their way out, laptops that won\'t boot the morning of something important, and Wi-Fi that won\'t reach across a unit. We carry common parts and aim to get people working again in a single visit rather than leaving a desk empty. On the residential side it\'s the familiar mix: cracked MacBook screens, worn batteries, and machines slowed to a crawl that an SSD and a clean-up bring straight back to life. We\'ll always tell you when an upgrade beats a replacement — it usually does. Liquid spills and sudden won\'t-turn-on faults round it out, and with those the speed of the call is what decides how much can be saved.', localLogistics: 'Tolworth is minutes from our New Malden base — one of the closest areas we cover — so same-day is the norm here rather than the exception, and we can often be more flexible on timing than elsewhere. Parking is generally manageable on the residential roads and we\'ll agree access for the A3 business units when you book. There\'s no callout charge, evenings and weekends cost the same as any weekday slot, and every repair carries the same 90-day warranty — with nothing to pay if we can\'t fix it.' },
  { slug: 'surbiton', name: 'Surbiton', postcode: 'KT6', borough: 'Kingston upon Thames', description: 'Surbiton and Hook area', localIntro: 'Surbiton\'s Art Deco station and riverside streets are full of London commuters, and a broken laptop the night before a work trip is one of our most common call-outs here. We\'re based just up the road in New Malden, so Surbiton visits are usually quick to arrange and often same-day. Surbiton is a commuter town in the truest sense — a lot of people here work in central London three or four days a week and do the rest from home, which means the home machine has to work and there\'s a narrow window to get it fixed. Evening appointments are more popular in KT6 than almost anywhere else we cover, and they don\'t cost extra. The housing is a mix of Victorian and Edwardian terraces, mansion blocks near the station and newer riverside flats, and the machines follow the same pattern: long-owned Macs that need reviving, and newer laptops that have taken a knock. We cover Surbiton, Berrylands and Tolworth on the same basis, usually on the same trip if it makes sense.', localRepairs: 'The commuter angle shapes the work: we get a lot of "it was fine yesterday and now it won\'t turn on" the night before something important, which is usually a failed boot, a dead battery or a drive on its way out, and usually fixable on the spot. Beyond the emergencies, Surbiton is steady upgrade territory — SSDs and RAM into machines that are five or six years old and perfectly good otherwise. It\'s the cheapest thing you can do to a slow computer, and we\'d rather tell you that than sell you a repair you don\'t need. The mansion blocks near the station throw up more Wi-Fi and networking jobs than average — thick walls and a router in the wrong place — and that\'s often a twenty-minute fix rather than a repair at all.', localLogistics: 'Surbiton is minutes from our New Malden base, so it\'s one of the fastest areas we cover and same-day is the norm rather than the exception. Parking is manageable on most residential roads but tighter near the station and the riverside flats, so we\'ll check access with you when you book. Evenings and weekends are no extra charge — for a commuter town, that\'s usually the point.' },
  { slug: 'esher', name: 'Esher', postcode: 'KT10', borough: 'Elmbridge', description: 'Esher and Claygate', localIntro: 'Esher is one of Surrey\'s more affluent towns, and a good share of our call-outs here are home workers around the High Street and out toward Sandown Park who\'d rather not hand an expensive Mac across a shop counter. Our engineer comes to you, works in front of you, and carries out most repairs on the spot — a discreet, in-home service that suits the area. We look after a lot of home offices in Esher, where the machine is a working tool and a few days without it genuinely costs something. That\'s the whole reason we work the way we do: we quote a fixed price before we start, and you\'re never without the device for longer than the job actually takes. We cover Esher, Claygate and the surrounding Elmbridge streets on the same basis, with no callout charge and the same fixed pricing wherever you are.', localRepairs: 'Esher\'s home-office lean shapes the work: a lot of it is keeping capable, well-cared-for machines running rather than resurrecting dead ones. Battery replacements, SSD and memory upgrades, and clearing the software clutter that slows an otherwise-healthy Mac are the regulars. Screen and keyboard repairs come up steadily too — Air and Pro panels we can usually carry and fit on-site — along with the occasional liquid spill at a kitchen-counter desk, where a fast call makes all the difference to what can be saved. Because so many people here run everything off a single machine, we spend a fair bit of time on backups and data recovery — making sure that before anything else happens, the important files are safe. Checking your backup actually runs is free advice we give on every visit.', localLogistics: 'Esher sits a little further out than our closest KT-postcode areas, but it\'s well within range, there\'s no callout charge, and same-day is usually workable if you call before 2pm. Parking is generally manageable on the residential roads, and for the High Street we\'ll agree the best access with you when you book rather than circling. Evenings and weekends cost no more than a weekday visit — which tends to suit a home-working schedule better anyway.' },
  { slug: 'teddington', name: 'Teddington', postcode: 'TW11', borough: 'Richmond upon Thames', description: 'Teddington and Hampton Wick', localIntro: 'Teddington\'s riverside streets and the studios nearby mean we see a real mix of home and creative-industry machines needing attention. We cover Teddington and Hampton Wick together, usually on the same trip, so getting an engineer to your door rarely takes long. Like neighbouring Richmond, Teddington has a strong media and creative thread running through it, which means a good number of the machines here are working tools — stuffed with projects and running near capacity. When one of those goes down mid-job, "leave it with us for a week" isn\'t an answer, and coming to your home studio or desk is exactly what our on-site service is built for. Alongside that there\'s the usual residential mix of family laptops and long-owned Macs, and we come to all of them the same way. We cover Teddington, Hampton Wick and the streets toward Bushy Park on the same basis, with the price agreed before we start.', localRepairs: 'Teddington\'s creative lean shapes a lot of the work: MacBooks that have filled up and slowed down, storage and memory upgrades to keep a working machine viable, and the recovery of drives — internal and external — that have stopped cooperating at the worst moment. Screen and battery repairs are steady too, and we can usually carry and fit the common Mac parts on-site in under an hour. From the residential side, family and student laptops add the familiar cracked screens, worn batteries and liquid spills. As everywhere, we treat backups as part of the job — for anyone whose income sits on one device, that safety net matters as much as the repair itself.', localLogistics: 'Teddington is across the river and a little further west for us, but well within range, with no callout charge, and same-day is usually workable if you call before 2pm. Parking is permit-controlled around much of the town, so we\'ll confirm access with you at booking rather than guessing — it\'s not a problem, we just plan for it. If you\'re in a studio or shared workspace we\'ll come to the desk. Evenings and weekends are no extra charge, which tends to suit a freelance schedule anyway.' },
  { slug: 'twickenham', name: 'Twickenham', postcode: 'TW1', borough: 'Richmond upon Thames', description: 'Twickenham and St Margarets', localIntro: 'On a rugby match day the roads around the stadium get busy, but the rest of Twickenham and St Margarets keep us busy year-round with MacBook and laptop repairs at people\'s homes. We plan around events like this so a booked visit isn\'t affected by matchday traffic. Away from the stadium, Twickenham is riverside streets, family houses and a strong thread of media and creative work thanks to the studios nearby — which means a good number of machines here are working tools stuffed with projects and running near capacity. We cover Twickenham and St Margarets together, coming to home offices, studios and kitchen tables alike, and we fix most faults in front of you. Whether it\'s a family laptop or a Mac that a freelancer\'s livelihood depends on, the service and the up-front pricing are the same.', localRepairs: 'Twickenham\'s creative and work-from-home leaning shapes the work: MacBooks that have filled up and slowed down, storage and memory upgrades to keep a working machine viable, and the recovery of drives — internal and external — that have stopped cooperating at the worst moment. Screen and battery repairs are steady too, and we can usually carry and fit the common Mac parts on-site. The machines here often run hot from heavy use, so a clean-out and a repaste to stop throttling is a job we do regularly. Family and student laptops from the residential streets add the usual cracked screens, worn batteries and liquid spills. As everywhere, we treat backups as part of the job — for anyone whose income sits on one device, that safety net matters as much as the repair.', localLogistics: 'Twickenham is a bit further west for us but well within range, with no callout charge, and same-day is usually workable if you call before 2pm. The one thing we plan around is match and event days at the stadium, when traffic seizes up — we\'ll simply schedule your visit to avoid it. Parking is permit-controlled around the town and St Margarets, so we\'ll confirm access with you at booking, and evenings and weekends are no extra charge.' },
  { slug: 'richmond', name: 'Richmond', postcode: 'TW9', borough: 'Richmond upon Thames', description: 'Richmond upon Thames', localIntro: 'We cover Richmond, Kew and St Margarets with a fully mobile service — ideal for the many media and creative professionals in the area who rely on their Macs for work and can\'t afford days without them. We come to your home studio or office and fix most faults on the spot. Richmond is the most Mac-heavy area we cover — full of people editing, designing and producing — often on machines that are stuffed with project files and running right at the limit of their storage. When one of those goes down mid-project, "leave it with us for a week" isn\'t an answer, and it\'s exactly the situation our on-site model was built for. Geographically it\'s a spread-out patch — Richmond town and the Green, up toward the Park, out to Kew and across to St Margarets and Twickenham — and we treat it as one area, usually covering more than one job per trip. It\'s also the area where we most often get asked about data rather than hardware, because the machine is replaceable and the work on it isn\'t.', localRepairs: 'Storage is the recurring Richmond theme: drives that are full, drives that are failing, and external drives full of footage that have stopped mounting. A lot of our work here is recovery and upgrade rather than classic breakage — getting the data off safely first, then making the machine fast enough to work on again. The creative machines also run hot: MacBook Pros that throttle, fans that never stop, and thermal problems from years of rendering, often a clean and a repaste rather than anything dramatic. We do the usual too — screens, batteries, liquid damage — but Richmond skews toward keeping a working machine working rather than resurrecting a dead one. If you\'re mid-project and something\'s going wrong, call before it fails properly; it\'s a much better conversation than the one after.', localLogistics: 'Richmond is a slightly longer run from New Malden than our KT-postcode areas, but there\'s still no callout charge and same-day is usually workable if you call before 2pm. Parking in Richmond town and around the Green is genuinely hard and largely permit-controlled, so we\'ll sort access with you at booking; if you\'re in a studio or shared office we\'ll come to the desk. Evenings and weekends are no extra charge, which tends to suit a freelance schedule better anyway.' },
  // South London
  { slug: 'croydon', name: 'Croydon', postcode: 'CR0', borough: 'Croydon', description: 'Croydon town centre and surrounding areas', localIntro: 'Croydon\'s tech and business district means a lot of the calls we get here are from offices around East Croydon and small firms that need a laptop or PC back up and running fast. We come to you across Croydon, Addiscombe and Purley — no need to drop anything off or wait days for a workshop. Croydon is really two jobs for us: the commercial core around East Croydon and the town centre, where downtime costs a business money and the priority is a same-day fix, and the residential sprawl out toward Addiscombe, Shirley and Purley, where it\'s more family machines and home setups. We handle both the same way — we come to the address, quote before we start, and fix most faults on the spot rather than carrying the machine away. For a busy commercial centre, that on-site, no-downtime approach is usually the whole point.', localRepairs: 'For Croydon\'s offices and small businesses, the common jobs are dead or failing PCs, drives on their way out, laptops that won\'t boot the morning of something important, and networks or Wi-Fi that won\'t reach across a unit. We carry common parts and aim to get people working again in a single visit rather than leaving a desk empty for a week. On the residential side around Addiscombe and Purley, it\'s the familiar mix of tired family laptops, cracked MacBook screens, worn batteries and machines slowed to a crawl that an SSD and a clean-up bring back to life. Data recovery and backups come up on both sides — a business that\'s never tested its backup, or a household with years of photos on one ageing drive — and safeguarding that is always the first thing we look at.', localLogistics: 'Croydon is a longer run from New Malden than our closest areas, but it\'s firmly within our range and there\'s no callout charge to any part of it. Same-day is usually workable if you call before 2pm, especially for business call-outs we can plan around. Parking is hard in the town centre and around East Croydon and much easier in the residential streets, so we\'ll agree the best access with you when you book. Evenings and weekends cost no more than a weekday visit.' },
  { slug: 'tooting', name: 'Tooting', postcode: 'SW17', borough: 'Wandsworth', description: 'Tooting Broadway and Tooting Bec', localIntro: 'Tooting\'s long, lively high street and market are at the centre of a genuinely mixed community, and our call-outs here range from student laptops to family MacBooks. We cover Tooting Broadway and Tooting Bec equally, with same-day visits available if you call before 2pm. It\'s one of the more varied parts of our patch — busy independent businesses along the high street, families in the terraces off Mitcham Road, and a younger renting crowd nearer the Broadway — and the machines are just as varied, from a shop\'s ageing till PC to a student\'s cracked MacBook Air. Whatever the device, we come to the address rather than asking anyone to queue somewhere with a broken laptop under their arm, and we quote the job before we touch it.', localRepairs: 'The mix in Tooting means we see a bit of everything: cracked screens and tired batteries on family and student MacBooks, slow and cluttered Windows laptops that need a clean-up and an SSD, and the occasional small-business machine that a local shop or café can\'t afford to be without. We carry common screens and batteries so a lot of these are one-visit jobs done in front of you. Liquid damage and won\'t-turn-on emergencies come up too, and with those the speed of the call makes the difference to what can be saved. For the independent businesses along the Broadway and Upper Tooting Road, we know a dead computer means a stalled day, so those we treat as priority and get to as fast as we can.', localLogistics: 'Tooting is an easy run for us and we\'re in the area regularly, so same-day visits before 2pm are usually simple to arrange. Parking is tight around the Broadway, the market and the high road, and easier on the residential streets off it, so we\'ll agree the best access with you at booking. There\'s no callout charge either way, and evening and weekend appointments cost exactly the same as a weekday slot.' },
  { slug: 'balham', name: 'Balham', postcode: 'SW12', borough: 'Wandsworth', description: 'Balham High Road area', localIntro: 'Balham sits between two commons and is popular with young professionals who work from home at least part of the week — which is exactly when a broken laptop hurts most. We visit flats and houses around Bedford Hill and Balham High Road with no callout charge and no need to carry anything to a shop. The area\'s Edwardian conversions and mansion flats are full of people running work, study and home life off a single machine, so when it goes down the priority is getting it back the same day rather than in a week. We come to you, diagnose the fault in front of you, and fix most things on the spot. Whether you\'re up near Wandsworth Common, down toward Tooting Bec, or on the streets either side of the High Road, it\'s the same visit and the same fixed-price-before-we-start approach.', localRepairs: 'Balham\'s work-from-home households keep us busy with the practical stuff that keeps a machine earning: battery replacements, SSD and memory upgrades, and clearing out the accumulated software clutter that makes a perfectly good Mac feel past it. Screen repairs are common too — Air and Pro panels we can usually carry and fit on-site. Liquid damage turns up more than people expect in a neighbourhood of home desks and kitchen-table working; the sooner we see it, the more we can usually save. And because so many people here have everything on one device, we spend a fair bit of time on backups and data — making sure that before anything else happens, the important files are safe and recoverable.', localLogistics: 'Balham is close to our patch and we\'re there often, so same-day is usually straightforward if you call before 2pm. Parking on the residential streets around Bedford Hill is permit-controlled and can be tight near the station and the High Road, so we\'ll check the best access with you when you book. Evenings and weekends are charged the same as any other slot, which tends to suit the part-remote professionals who make up a lot of the area.' },
  { slug: 'streatham', name: 'Streatham', postcode: 'SW16', borough: 'Lambeth', description: 'Streatham High Road and surrounding', localIntro: 'Streatham\'s long high road and the streets around Streatham Common give us a steady flow of both home and small-business call-outs. We treat Streatham as core territory, so most repairs booked before 2pm are seen the same day. One of the longest high streets in south London runs through the middle of the area, lined with independent shops and small offices, while the roads off it toward the Common and up Streatham Hill are mostly families and long-term residents. That gives us a real range of work — a salon\'s booking PC one visit, a family MacBook the next — and we come to all of them rather than running a shop for people to bring machines into. From Streatham Hill down to Norbury, it\'s the same door-to-door service with the price agreed up front.', localRepairs: 'Family machines are the backbone of the Streatham work: laptops that have slowed with age, run low on storage, or picked up a knock, plus MacBooks needing a new screen or battery. A lot of these are straightforward on-site fixes, and where a machine just feels tired an SSD and a clean install usually transform it far more cheaply than a replacement. On the high road, small businesses bring their own needs — a till or booking PC that won\'t start, patchy Wi-Fi that won\'t reach the back of a unit, or a laptop that\'s the only one in the building. Liquid spills and sudden won\'t-boot faults round out the mix, and as always the quicker we see those, the more we can usually recover.', localLogistics: 'Streatham is well within our regular range, so same-day is the norm if you call before 2pm. Parking varies a lot — genuinely difficult along the High Road, much easier on the residential streets toward the Common — so we\'ll confirm the best spot to aim for when you book. No callout charge applies anywhere in the area, and evenings and weekends are priced the same as any weekday visit.' },
  { slug: 'clapham', name: 'Clapham', postcode: 'SW4', borough: 'Lambeth', description: 'Clapham Common and Clapham South', localIntro: 'Clapham is full of young professionals and flat-shares where a broken MacBook or laptop can\'t wait for a shop appointment. We visit homes around Clapham Common, Clapham North and Clapham South evenings and weekends, so a repair fits around your work rather than the other way round. The streets off the Common and around the Old Town are dense with converted flats and shared houses, and for a lot of the people here the laptop is the only computer they own and the thing they earn a living on. That\'s the situation our mobile service was built for — we come to the flat, work at the kitchen table, and hand the machine back working rather than asking you to be without it for a week. From the High Street down to Abbeville Road and across to Clapham South, it\'s all the same visit and the same no-callout-charge promise.', localRepairs: 'The flat-share and young-professional mix means most Clapham call-outs are laptops that are heavily used and lightly maintained: batteries that no longer hold a charge, screens cracked in a bag or on a desk, and machines that have simply filled up and slowed down. A clean install and an SSD often bring an apparently dead laptop back to life for a fraction of a replacement. Liquid damage comes up regularly — a drink into a MacBook is a classic — and speed matters, so it\'s always worth calling before writing the machine off. We also help a lot of people who\'ve never backed anything up and have suddenly realised the risk; getting a safe backup running is advice we give free on every visit, alongside the repair itself.', localLogistics: 'Clapham is a straightforward run for us and we\'re across the area regularly, so same-day visits booked before 2pm are usually easy to arrange. Parking around the Common and the Old Town is permit-heavy and busy, especially at weekends, so we\'ll sort out access with you at booking. Evening and weekend slots cost no more than any other — for a neighbourhood of full-time professionals, that\'s usually the only time that works, and we\'re happy to fit it.' },
  { slug: 'brixton', name: 'Brixton', postcode: 'SW9', borough: 'Lambeth', description: 'Brixton and Stockwell', localIntro: 'Brixton\'s markets and creative businesses mean we repair everything here from a stallholder\'s laptop to a family iMac in a flat above a shop near Electric Avenue. We come to you anywhere in Brixton and Stockwell — no shop visit needed, and the price agreed before we start. It\'s one of the more varied parts of our patch. There are the independent businesses in and around the market, where a dead till PC or a booking laptop stops trading cold; the creative and music thread the area is known for, running on Macs full of projects; and the dense residential streets of flats and shared houses, where the laptop is often the only computer in the home and the thing someone earns a living on. We come to all of them the same way — to the address, working in front of you, finishing on the spot wherever we can. We cover Brixton, Stockwell and the streets toward Herne Hill on the same basis.', localRepairs: 'The mix in Brixton means we see a bit of everything. For the independent businesses it\'s dead till and booking PCs, failing drives, and Wi-Fi that won\'t reach the back of a unit — jobs we treat as priority because a stalled machine means a stalled day. On the residential side it\'s the familiar run of cracked MacBook screens, worn batteries, and heavily-used laptops that have filled up and slowed down — a clean install and an SSD often bring an apparently dead machine back for a fraction of a replacement. Liquid spills and won\'t-turn-on emergencies come up too, and the sooner we see those, the more we can usually save.', localLogistics: 'Brixton is one of the longer runs from our New Malden base, but it\'s firmly within our range and there\'s no callout charge to any part of it. Same-day is usually workable if you call before 2pm, especially for business call-outs we can plan around. Parking is genuinely difficult around the market, the centre and Electric Avenue, and easier on the residential streets off them, so we\'ll agree the best access and meeting point with you at booking. Evenings and weekends are priced the same as any weekday visit.' },
  { slug: 'vauxhall', name: 'Vauxhall', postcode: 'SW8', borough: 'Lambeth', description: 'Vauxhall and Nine Elms', localIntro: 'The new-build towers around Vauxhall and Nine Elms are full of professionals who can\'t afford downtime on a work laptop, and we\'re a regular call-out for exactly that reason. We visit apartments and offices across the area, usually the same day if you call before 2pm.' },
  { slug: 'battersea', name: 'Battersea', postcode: 'SW11', borough: 'Wandsworth', description: 'Battersea and Clapham Junction', localIntro: 'With the Power Station redevelopment and Battersea Park nearby, this is one of our busier South London patches — everything from a cracked MacBook screen to a slow family PC. We cover Battersea through to Clapham Junction on the same visit where it makes sense. The area has changed enormously, and the new-build towers around the Power Station and Nine Elms fringe are full of professionals whose work depends on a laptop that simply has to keep running. Alongside them are the older terraces around the Park and up toward Lavender Hill, where the machines tend to have been in the family for years. We come to apartments, houses and home offices right across that range, diagnose the fault while you watch, and fix most things without the device ever leaving your side.', localRepairs: 'Battersea\'s professional, apartment-heavy population means a lot of the work is keeping capable machines running: battery replacements, SSD upgrades, and clearing the clutter that slows a Mac that\'s otherwise fine. Screen repairs are common — Air and Pro panels we can usually fit on-site in under an hour — and liquid damage turns up wherever people work from a kitchen counter or a desk beside a coffee. In the newer flats we also get a fair number of Wi-Fi and networking jobs, where thick modern walls and a router in the wrong spot cause more trouble than any actual fault. The older houses around the Park lean more toward ageing family laptops and desktops that need reviving rather than replacing, which is usually a cheaper and quicker job than people assume.', localLogistics: 'Battersea and Clapham Junction are a comfortable run for us, so same-day visits booked before 2pm are usually easy. Parking around Lavender Hill, the Junction and the new developments is difficult and largely permit- or barrier-controlled, so for those we\'ll sort access and the best meeting point with you at booking. There\'s no callout charge, and evening and weekend appointments are the same price as any weekday slot — handy for the many full-time professionals here.' },
  { slug: 'putney', name: 'Putney', postcode: 'SW15', borough: 'Wandsworth', description: 'Putney and Roehampton', localIntro: 'Putney\'s riverside setting and the streets running up from the bridge are home to a lot of professionals and families we\'ve helped with everything from liquid-damaged MacBooks to slow desktop PCs. We cover Putney and Roehampton together, with no callout charge either way. Putney High Street and the roads off Lower Richmond Road are busy with people who work from home at least part of the week, so a broken laptop here usually means a lost working day rather than a minor inconvenience — which is exactly why we come to you and try to finish on the spot. Out toward Roehampton, with the university close by, we see more student machines: the laptop that has to last until the end of term. Whether you\'re in a riverside flat, a terrace off the Upper Richmond Road, or a house up toward the Heath, the service is the same — we come to your door and fix most faults in front of you.', localRepairs: 'Screen and battery work makes up a lot of what we do in Putney — a MacBook Air that\'s taken a knock, or an older Mac that no longer lasts a morning on charge. We carry the common Air and Pro parts so most of these are done on-site. Liquid damage is the other recurring one, and with Putney\'s mix of home offices a coffee into a keyboard is more common than you\'d think; if you get to us quickly the outlook is usually far better than people fear. We also do a steady stream of speed-ups — SSD and memory upgrades on machines that are a few years old and perfectly capable with the right parts — and we\'ll always tell you when that\'s a smarter spend than a full replacement. Student laptops from the Roehampton side tend to be screens, hinges and charging faults.', localLogistics: 'Putney sits a little further west of our New Malden base, but there\'s still no callout charge and same-day is usually workable if you call before 2pm. Parking around the High Street and the station is permit-controlled and tight, so we\'ll agree access with you when you book rather than circling. Riverside and Heath-side streets are generally easier. Evenings and weekends are no extra charge, which suits the work-from-home crowd who can\'t break off mid-afternoon.' },
  { slug: 'bromley', name: 'Bromley', postcode: 'BR1', borough: 'Bromley', description: 'Bromley town centre', localIntro: 'Bromley\'s busy town centre and the streets around the Glades shopping centre keep us regularly on the road here, fixing laptops and Macs for households and local offices alike. As with the rest of the borough, we quote a fixed price before starting and travel to you at no extra cost.' },
  { slug: 'beckenham', name: 'Beckenham', postcode: 'BR3', borough: 'Bromley', description: 'Beckenham and Elmers End', localIntro: 'Beckenham\'s leafy residential streets are a common call-out for slowing-down family computers and MacBooks that need a battery or screen replaced. We cover Beckenham and Elmers End on the same basis as the rest of Bromley — no callout charge, same-day where possible.' },
  // Central / West London
  { slug: 'chelsea', name: 'Chelsea', postcode: 'SW3', borough: 'Kensington and Chelsea', description: 'Chelsea and Knightsbridge', localIntro: 'We offer a discreet, professional in-home repair service across Chelsea, Knightsbridge and the King\'s Road area. For residents who\'d rather not hand an expensive Mac to a high-street shop, our engineer comes to you and carries out most repairs on-site while you watch.' },
  { slug: 'fulham', name: 'Fulham', postcode: 'SW6', borough: 'Hammersmith and Fulham', description: 'Fulham Broadway and Parsons Green', localIntro: 'Fulham\'s mix of young professionals and families around Fulham Broadway and Parsons Green keeps us busy with everything from MacBook Pro screen repairs to home network troubleshooting. We come to your door rather than asking you to carry a laptop into town.' },
  { slug: 'hammersmith', name: 'Hammersmith', postcode: 'W6', borough: 'Hammersmith and Fulham', description: 'Hammersmith and Shepherds Bush', localIntro: 'Hammersmith\'s office towers around the Broadway mean a good number of our call-outs here are people who can\'t afford to be without a work laptop for even a day. We also cover the residential streets towards Shepherds Bush on the same visit.' },
  { slug: 'earls-court', name: 'Earls Court', postcode: 'SW5', borough: 'Kensington and Chelsea', description: 'Earls Court and West Kensington', localIntro: 'Earls Court\'s mix of short lets, students and long-term residents means we see a real variety of devices, from ageing MacBooks to brand-new gaming laptops. We\'re happy to visit shared flats as readily as houses, with the same no callout charge throughout.' },
  { slug: 'kensington', name: 'Kensington', postcode: 'W8', borough: 'Kensington and Chelsea', description: 'Kensington and Holland Park', localIntro: 'Kensington\'s townhouses and the streets around Holland Park are some of our more discreet call-outs — residents who\'d rather not hand an expensive Mac over a shop counter. Our engineer comes to you directly and carries out most repairs on the spot.' },
  // East / SE London
  { slug: 'lewisham', name: 'Lewisham', postcode: 'SE13', borough: 'Lewisham', description: 'Lewisham town centre', localIntro: 'Lewisham\'s town centre and shopping centre keep us busy with both home visits and small offices that need a laptop back up fast. We cover all of Lewisham on the same basis as the rest of South East London — no callout charge, same-day where we can.' },
  { slug: 'catford', name: 'Catford', postcode: 'SE6', borough: 'Lewisham', description: 'Catford and Hither Green', localIntro: 'Catford\'s residential streets around the Broadway are a regular call-out for us, usually MacBook batteries, cracked screens or a PC that\'s stopped booting properly. We treat Catford and Hither Green as one patch, so a visit is easy to arrange.' },
  { slug: 'greenwich', name: 'Greenwich', postcode: 'SE10', borough: 'Greenwich', description: 'Greenwich and Blackheath', localIntro: 'Between the park, the Cutty Sark and the mix of residents and visitors, Greenwich keeps us on our toes — we\'ve fixed laptops for long-term locals and people working remotely from short lets alike. We cover Greenwich and Blackheath together, with no shop visit ever required.' },
  
  // North London
  { slug: 'islington', name: 'Islington', postcode: 'N1', borough: 'Islington', description: 'Islington and Angel area', localIntro: 'Around Angel and Upper Street there are countless startups, agencies and freelancers who live on their Macs. We come to your home or co-working space across Islington, Barnsbury and Canonbury and get you back to work fast — most repairs done on-site in under an hour.' },
  { slug: 'camden', name: 'Camden', postcode: 'NW1', borough: 'Camden', description: 'Camden Town and Chalk Farm', localIntro: 'Camden\'s creative and music-industry crowd around the Lock and Chalk Farm often rely on laptops for their work, which is exactly when a screen crack or battery fault can\'t wait. We come to your home or studio and get most repairs done on the spot.' },
  { slug: 'finchley', name: 'Finchley', postcode: 'N3', borough: 'Barnet', description: 'Finchley and Woodhouse', localIntro: 'Finchley\'s quiet residential streets mean most of our call-outs here are family laptops and older iMacs that have slowed down over the years. We cover Finchley and Woodhouse on the same visit, with no callout charge added to the bill.' },
  { slug: 'barnet', name: 'Barnet', postcode: 'EN5', borough: 'Barnet', description: 'High Barnet and Chipping Barnet', localIntro: 'High Barnet\'s market-town history hasn\'t stopped it becoming a solidly residential and commuter area, and that\'s reflected in the mix of laptops and desktops we\'re called out to fix. We travel to Chipping Barnet and the surrounding streets as part of our standard coverage.' },
  { slug: 'enfield', name: 'Enfield', postcode: 'EN1', borough: 'Enfield', description: 'Enfield Town and surrounding areas', localIntro: 'Enfield Town\'s shopping streets and the quieter residential roads nearby give us a broad mix of repairs, from small business PCs to family MacBooks. We cover all of Enfield with the same no callout charge and same-day service we offer across London.' },
  { slug: 'haringey', name: 'Haringey', postcode: 'N8', borough: 'Haringey', description: 'Haringey and Hornsey', localIntro: 'Around Crouch End and Hornsey, Haringey\'s hilly streets and independent high streets are home to a lot of freelancers and home workers who call us the moment a laptop stops behaving. We visit homes and small studios across the area, usually the same day if booked before 2pm.' },
  
  // East London
  { slug: 'stratford', name: 'Stratford', postcode: 'E15', borough: 'Newham', description: 'Stratford and Queen Elizabeth Olympic Park', localIntro: 'Stratford has changed enormously since the Olympics, and the mix of new-build flats around the park and offices near Westfield means we\'re often called out for both home and work laptops in the same week. We cover the whole area, including Maryland and the streets around the Olympic Park.' },
  { slug: 'canary-wharf', name: 'Canary Wharf', postcode: 'E14', borough: 'Tower Hamlets', description: 'Canary Wharf and Isle of Dogs', localIntro: 'Canary Wharf runs on laptops, and downtime is expensive. We provide fast on-site laptop, MacBook and PC repair to offices and apartments across the Wharf and the Isle of Dogs, fitting around meetings and working hours so a hardware fault doesn\'t cost you a day.' },
  { slug: 'hackney', name: 'Hackney', postcode: 'E8', borough: 'Hackney', description: 'Hackney Central and Dalston', localIntro: 'Hackney Central and Dalston are full of freelancers, small studios and agencies who can\'t afford a laptop being out of action, which is exactly the gap our on-site service fills. We visit homes, flats and workspaces across the borough with no callout charge.' },
  { slug: 'shoreditch', name: 'Shoreditch', postcode: 'E1', borough: 'Hackney', description: 'Shoreditch and Hoxton', localIntro: 'Shoreditch\'s startups and agencies around Old Street live on their laptops, and a dead MacBook mid-project is the kind of emergency we\'re built for. We come straight to the office or co-working space rather than asking anyone to lose an afternoon at a repair shop.' },
  { slug: 'ilford', name: 'Ilford', postcode: 'IG1', borough: 'Redbridge', description: 'Ilford and Seven Kings', localIntro: 'Ilford\'s busy town centre and the residential streets around Seven Kings keep us regularly on the road here, mostly family laptops and the odd small business PC. We cover the whole of Ilford with no callout charge and a 90-day warranty on every repair.' },
  { slug: 'romford', name: 'Romford', postcode: 'RM1', borough: 'Havering', description: 'Romford town centre', localIntro: 'Romford\'s market and shopping streets sit alongside a lot of family housing, and that mix shows up in our call-outs — everything from a teenager\'s gaming laptop to a parent\'s work MacBook. We cover Romford town centre and the surrounding estates on the same basis as the rest of East London.' },

  // Further West London & Middlesex
  { slug: 'chiswick', name: 'Chiswick', postcode: 'W4', borough: 'Hounslow', description: 'Chiswick and Turnham Green', localIntro: 'Chiswick\'s riverside streets and the shops along the High Road are home to a lot of families and professionals who\'d rather not lose a day taking a laptop into town. We visit Chiswick and Turnham Green with the same no-shop-visit approach we use everywhere else.' },
  { slug: 'ealing', name: 'Ealing', postcode: 'W5', borough: 'Ealing', description: 'Ealing Broadway and West Ealing', localIntro: 'We cover Ealing Broadway, West Ealing and Ealing Common with a doorstep repair service that suits the area\'s many families and home workers. From a child\'s cracked laptop screen before school to a work MacBook that won\'t boot, we come to you and sort it the same day where we can.' },
  { slug: 'hounslow', name: 'Hounslow', postcode: 'TW3', borough: 'Hounslow', description: 'Hounslow Central and West', localIntro: 'Hounslow\'s proximity to Heathrow means a lot of our call-outs here are people who need a laptop working again before a flight, alongside the usual mix of family and small-business repairs. We cover Hounslow Central and West on the same visit wherever possible.' },
  { slug: 'uxbridge', name: 'Uxbridge', postcode: 'UB8', borough: 'Hillingdon', description: 'Uxbridge town centre', localIntro: 'With Brunel University London based here, Uxbridge has a strong student population alongside its usual residential streets, and we see plenty of both — cracked laptop screens are a particularly common call in term time. We cover the whole town centre and surrounding halls of residence.' },
  { slug: 'hayes', name: 'Hayes', postcode: 'UB3', borough: 'Hillingdon', description: 'Hayes and Harlington', localIntro: 'Hayes and Harlington\'s mix of industrial estates and residential streets near Heathrow keeps our call-outs varied, from office PCs to family laptops. We travel here as part of our standard Greater London coverage, with no callout charge either way.' },

  // South East London Additions
  { slug: 'dulwich', name: 'Dulwich', postcode: 'SE21', borough: 'Southwark', description: 'Dulwich and West Dulwich', localIntro: 'Dulwich\'s leafy streets around the Picture Gallery and the local schools mean a lot of our call-outs are family laptops and MacBooks that have taken a knock. We cover Dulwich and West Dulwich together, with the same 90-day warranty as everywhere else.' },
  { slug: 'orpington', name: 'Orpington', postcode: 'BR6', borough: 'Bromley', description: 'Orpington and Petts Wood', localIntro: 'Orpington\'s suburban streets and the shops around the high street give us a steady flow of family repairs — MacBook batteries, screen cracks and PCs that have simply slowed with age. We cover Orpington and Petts Wood on the same visit, no callout charge.' },
  { slug: 'peckham', name: 'Peckham', postcode: 'SE15', borough: 'Southwark', description: 'Peckham and Nunhead', localIntro: 'Peckham\'s arts scene and the studios around Copeland Park sit alongside its usual residential streets, and we see both — a photographer\'s MacBook one day, a family laptop the next. We cover Peckham and Nunhead as standard, with no shop visit ever required.' },
  { slug: 'dartford', name: 'Dartford', postcode: 'DA1', borough: 'Dartford', description: 'Dartford and surrounding areas', localIntro: 'Dartford\'s town centre and residential streets sit at the eastern edge of our regular coverage, and we still offer the same same-day, no-callout-charge service here as we do closer to base. Most repairs — MacBook and Windows alike — are done on-site within the hour.' },

  // More Surrey / Greater London Border Additions
  { slug: 'weybridge', name: 'Weybridge', postcode: 'KT13', borough: 'Elmbridge', description: 'Weybridge and Oatlands', localIntro: 'Weybridge\'s history at Brooklands and its reputation as one of Surrey\'s more affluent towns mean we\'re often asked to repair MacBooks and iMacs discreetly at home rather than dropping them at a shop. We cover Weybridge and Oatlands on the same basis as the rest of Elmbridge.' },
  { slug: 'walton-on-thames', name: 'Walton-on-Thames', postcode: 'KT12', borough: 'Elmbridge', description: 'Walton-on-Thames and Hersham', localIntro: 'Walton-on-Thames\' riverside setting and busy high street bring us a good mix of family and professional repairs, from a teenager\'s laptop to a home-office MacBook. We cover Walton and Hersham together, with no callout charge for the visit.' },
  { slug: 'leatherhead', name: 'Leatherhead', postcode: 'KT22', borough: 'Mole Valley', description: 'Leatherhead and Fetcham', localIntro: 'Leatherhead sits right on the edge of the Surrey Hills, and while it\'s a smaller town than some on our list, we cover it with exactly the same same-day, no-fix-no-fee service. Most call-outs here are family laptops and older desktop PCs that need a service.' },
  { slug: 'cobham', name: 'Cobham', postcode: 'KT11', borough: 'Elmbridge', description: 'Cobham and Stoke d\'Abernon', localIntro: 'Cobham is one of Surrey\'s most affluent villages — home to Chelsea FC\'s training ground as well as plenty of professionals working from home — and we visit both business and residential addresses here with the same discretion we offer in Chelsea itself. We quote a fixed price before starting and never leave until you\'re satisfied.' },
  { slug: 'dorking', name: 'Dorking', postcode: 'RH4', borough: 'Mole Valley', description: 'Dorking and surrounding villages', localIntro: 'Dorking\'s position at the foot of Box Hill and the North Downs makes it one of the further-flung parts of our patch, but we still travel out for MacBook and laptop repairs with no callout charge. Most visits here are family homes and the occasional home-based business.' },
  { slug: 'woking', name: 'Woking', postcode: 'GU21', borough: 'Woking', description: 'Woking town centre', localIntro: 'Woking\'s busy railway hub and the shops around the town centre mean plenty of commuters rely on a working laptop the moment they\'re home, which is exactly the gap our same-day service fills. We cover the whole of Woking with no need to visit a shop.' },
  { slug: 'guildford', name: 'Guildford', postcode: 'GU1', borough: 'Guildford', description: 'Guildford and surrounding areas', localIntro: 'As Surrey\'s county town, Guildford has a large student population from the University of Surrey alongside its usual residential streets, and we see both — cracked laptop screens in term time, family MacBooks the rest of the year. We cover the town centre and surrounding halls with the same fixed-price, no-callout-charge approach as everywhere else.' },

  // Previously missing London boroughs
  { slug: 'barking', name: 'Barking', postcode: 'IG11', borough: 'Barking and Dagenham', description: 'Barking town centre and Dagenham', localIntro: 'Barking\'s town centre, close to the Abbey ruins, and the residential streets around it are part of our regular East London coverage, mostly family laptops and small office PCs. We travel here with no callout charge and the same 90-day warranty as every other repair.' },
  { slug: 'bexleyheath', name: 'Bexleyheath', postcode: 'DA6', borough: 'Bexley', description: 'Bexleyheath and Sidcup', localIntro: 'Bexleyheath\'s Broadway shopping centre and the surrounding residential streets keep us busy with a steady mix of family and small-business repairs. We cover Bexleyheath and Sidcup on the same visit, with no need to bring anything to a shop.' },
  { slug: 'wembley', name: 'Wembley', postcode: 'HA9', borough: 'Brent', description: 'Wembley and surrounding areas', localIntro: 'Wembley\'s landmark stadium arch is hard to miss, but most of our call-outs here are in the residential streets around it — family laptops, ageing desktop PCs and the occasional gaming rig. We cover the whole Wembley area with no callout charge and same-day visits where we can manage it.' },
  { slug: 'harrow', name: 'Harrow', postcode: 'HA1', borough: 'Harrow', description: 'Harrow town centre and Harrow-on-the-Hill', localIntro: 'Harrow-on-the-Hill\'s famous school sits above a much larger residential town, and it\'s the family homes and local offices in Harrow itself that make up most of our call-outs. We cover the full town centre and surrounding streets with the same fixed-price approach as everywhere else.' },
  { slug: 'walthamstow', name: 'Walthamstow', postcode: 'E17', borough: 'Waltham Forest', description: 'Walthamstow and surrounding areas', localIntro: 'Walthamstow\'s long market and the wetlands nearby sit alongside a growing number of young families and professionals, and our call-outs reflect that mix — MacBooks, gaming PCs and the odd small-business laptop. We cover the whole of Walthamstow with no callout charge.' },
  { slug: 'westminster', name: 'Westminster', postcode: 'SW1', borough: 'Westminster', description: 'Westminster, Victoria and Marylebone', localIntro: 'Around Victoria and Marylebone, Westminster is dense with offices and apartments where a broken work laptop can\'t wait for a shop appointment. We come straight to your desk or door, wherever in the borough you are, and diagnose the fault in front of you.' },

  // Guildford / Crawley corridor - the areas we cover beyond the M25
  { slug: 'redhill', name: 'Redhill', postcode: 'RH1', borough: 'Reigate and Banstead', description: 'Redhill town centre', localIntro: 'Redhill\'s railway junction brings a lot of commuters through the town, and our call-outs here are usually laptops that need to be working again before the next train into London. We cover Redhill town centre and the surrounding streets with no callout charge.' },
  { slug: 'reigate', name: 'Reigate', postcode: 'RH2', borough: 'Reigate and Banstead', description: 'Reigate and surrounding areas', localIntro: 'Reigate\'s position beneath Reigate Hill and its reputation as one of Surrey\'s more affluent towns mean a lot of our call-outs are home-office MacBooks and family laptops. We travel here as part of our standard coverage, with the same 90-day warranty as everywhere else.' },
  { slug: 'banstead', name: 'Banstead', postcode: 'SM7', borough: 'Reigate and Banstead', description: 'Banstead and surrounding areas', localIntro: 'Banstead\'s village feel and the open space of Banstead Downs make it one of our quieter, more residential call-outs — mostly family laptops and the odd ageing desktop. We cover Banstead with the same fixed-price, no-callout-charge service as the rest of Surrey.' },
  { slug: 'caterham', name: 'Caterham', postcode: 'CR3', borough: 'Tandridge', description: 'Caterham and Whyteleafe', localIntro: 'Caterham sits right on the edge of the North Downs, and while it\'s one of the further reaches of our patch, we still travel out for the same same-day repairs and no-fix-no-fee guarantee. Most visits here are family homes in Caterham and neighbouring Whyteleafe.' },
  { slug: 'oxted', name: 'Oxted', postcode: 'RH8', borough: 'Tandridge', description: 'Oxted and Limpsfield', localIntro: 'Oxted and Limpsfield\'s mix of commuter housing and North Downs countryside makes for a quieter corner of our coverage area, but the service is identical to anywhere closer to London — fixed price, no callout charge, 90-day warranty. Most call-outs here are family laptops and home-office Macs.' },
  { slug: 'staines', name: 'Staines', postcode: 'TW18', borough: 'Spelthorne', description: 'Staines-upon-Thames and surrounding areas', localIntro: 'Staines\' riverside setting and its closeness to Heathrow mean we\'re often fixing laptops for people who travel for work as much as those who work from home. We cover the whole of Staines-upon-Thames with no callout charge and same-day visits where possible.' },
  { slug: 'egham', name: 'Egham', postcode: 'TW20', borough: 'Runnymede', description: 'Egham and Englefield Green', localIntro: 'Egham is home to Royal Holloway, University of London, so alongside the usual family and home-office repairs we see a fair number of student laptops with cracked screens or failing batteries. We cover Egham and Englefield Green together, with the same fixed-price approach as everywhere else.' },
  { slug: 'chertsey', name: 'Chertsey', postcode: 'KT16', borough: 'Runnymede', description: 'Chertsey town centre', localIntro: 'Chertsey\'s riverside streets, not far from Thorpe Park, are a regular but quieter part of our Surrey coverage — mostly family laptops and older desktop PCs. We travel here with no callout charge, same as the rest of Runnymede.' },
  { slug: 'addlestone', name: 'Addlestone', postcode: 'KT15', borough: 'Runnymede', description: 'Addlestone and New Haw', localIntro: 'Addlestone\'s redeveloped town centre sits alongside plenty of family housing, and our call-outs here are the usual mix of MacBooks, Windows laptops and slow-running PCs. We cover Addlestone and New Haw on the same visit, with no need to bring anything to a shop.' },
  { slug: 'crawley', name: 'Crawley', postcode: 'RH10', borough: 'Crawley', description: 'Crawley town centre and Gatwick area', localIntro: 'Crawley\'s new-town layout and its closeness to Gatwick mean a good number of our call-outs are travellers needing a laptop fixed before a flight, alongside the usual family and office repairs. We cover the whole of Crawley with the same same-day, no-fix-no-fee service as the rest of our patch.' }
];

export function getLocation(slug: string): Location | undefined {
  return locations.find((l) => l.slug === slug);
}

export interface LocationGroup {
  borough: string;
  locations: Location[];
}

// Used by the "Areas We Cover" index page so all locations are browsable from
// one place, grouped by borough/district rather than one long flat list.
export function getLocationsGroupedByBorough(): LocationGroup[] {
  const groups = new Map<string, Location[]>();

  for (const location of locations) {
    const key = location.borough || 'Other';
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(location);
  }

  return Array.from(groups.entries())
    .map(([borough, locs]) => ({
      borough,
      locations: [...locs].sort((a, b) => a.name.localeCompare(b.name)),
    }))
    .sort((a, b) => a.borough.localeCompare(b.borough));
}

// Postcode-area letters (e.g. "KT" from "KT3") are a good geographic proximity
// signal. We surface genuinely nearby areas on each location page so every page
// has a unique block of internal links and localised content rather than a pure
// template — this avoids the thin/duplicate-content SEO problem.
function postcodeArea(postcode?: string): string {
  return (postcode || '').replace(/[0-9].*$/, '').toUpperCase();
}

export function getNearbyLocations(slug: string, limit = 6): Location[] {
  const current = getLocation(slug);
  if (!current) return [];

  const currentArea = postcodeArea(current.postcode);
  const others = locations.filter((l) => l.slug !== current.slug);

  const scored = others
    .map((l) => {
      let score = 0;
      if (l.borough && l.borough === current.borough) score += 3;
      if (currentArea && postcodeArea(l.postcode) === currentArea) score += 2;
      return { location: l, score };
    })
    .filter((entry) => entry.score > 0)
    .sort((a, b) => b.score - a.score);

  const nearby = scored.map((entry) => entry.location);

  // Fall back to a few other London areas if a location has no scored neighbours,
  // so the "areas we also cover" block is never empty.
  if (nearby.length < limit) {
    for (const l of others) {
      if (nearby.length >= limit) break;
      if (!nearby.includes(l)) nearby.push(l);
    }
  }

  return nearby.slice(0, limit);
}

export interface LocationFAQ {
  q: string;
  a: string;
}

// Four differently-worded FAQ sets so the FAQPage schema isn't a byte-identical
// block repeated across all 81 location pages — each location gets one variant,
// chosen deterministically from its slug so the assignment is stable across builds.
const LOCATION_FAQ_VARIANTS: ((loc: Location) => LocationFAQ[])[] = [
  (loc) => [
    { q: `Do you offer same-day Mac repair in ${loc.name}?`, a: `Yes - we offer same-day callouts in ${loc.name} and surrounding areas. Book before 2pm and we can typically visit the same day.` },
    { q: 'Is there a callout charge?', a: `There is no callout charge for visits to ${loc.name}. You only pay for the repair itself, and only if we fix it.` },
    { q: `What areas near ${loc.name} do you also cover?`, a: `We cover all of ${loc.borough || loc.name} and surrounding areas. We travel across all of Greater London, so if you are nearby, we can almost certainly come to you.` },
    { q: 'What devices do you repair?', a: 'We repair MacBook Pro, MacBook Air, iMac, Mac Mini, all Windows laptops (HP, Dell, Lenovo, Asus, Acer), gaming PCs and more.' },
    { q: 'How do I book a repair?', a: `Call us on 0737 834 9222 or email info@werepairmac.co.uk. We will arrange a convenient time to visit your home or workplace in ${loc.name}.` },
  ],
  (loc) => [
    { q: `How quickly can an engineer reach ${loc.name}?`, a: `Most bookings in ${loc.name} are seen the same day if you call before 2pm. Evening and weekend visits are available too, so a repair fits around your schedule rather than the other way round.` },
    { q: `Will I be charged just for you to visit ${loc.name}?`, a: `No - there is no callout fee anywhere in ${loc.borough || loc.name}. You only pay for parts and labour, and nothing at all if we can't fix the problem.` },
    { q: 'What kind of computer problems do you handle?', a: 'Everything from cracked MacBook screens and failing batteries to Windows laptops that won\'t boot, slow PCs, virus infections and data recovery from failed drives.' },
    { q: `Do you cover the wider ${loc.borough || 'London'} area as well?`, a: `Yes - ${loc.name} sits within our regular coverage area, and we regularly visit the surrounding neighbourhoods on the same trip.` },
    { q: 'How do I arrange a visit?', a: `Phone 0737 834 9222 or email info@werepairmac.co.uk with a short description of the fault, and we'll confirm a time to come to you in ${loc.name}.` },
  ],
  (loc) => [
    { q: `What's the fastest way to get a repair booked in ${loc.name}?`, a: `Call 0737 834 9222 - most ${loc.name} callouts booked before 2pm are seen the same day, with no need to bring anything to a shop.` },
    { q: 'Do you charge extra for parts and labour separately, or is it all inclusive?', a: 'We quote labour (£100/hr) and any parts separately, upfront and before we start, so there are no surprises on the final bill.' },
    { q: `Is ${loc.name} within your standard service area?`, a: `Yes, ${loc.name} and the rest of ${loc.borough || 'the surrounding area'} are covered as standard, with no callout charge added to your bill.` },
    { q: 'What if the repair doesn\'t work?', a: 'Every repair carries a 90-day parts and labour warranty. If the same fault comes back, we return and fix it at no extra cost.' },
    { q: `Can you come to an office as well as a home in ${loc.name}?`, a: `Yes - we visit homes, offices and co-working spaces across ${loc.name} equally, and can work around meeting times if needed.` },
  ],
  (loc) => [
    { q: `Can someone come to my home in ${loc.name} rather than me bringing the laptop in?`, a: `Yes - that's the whole model. Our engineer travels to you in ${loc.name} and carries out most repairs on-site, in front of you.` },
    { q: 'Which brands and devices are you able to fix?', a: 'Mac and MacBook models of every generation, plus Windows laptops from HP, Dell, Lenovo, Asus and Acer, desktop PCs, and gaming consoles.' },
    { q: `Does it cost more because I'm in ${loc.name}?`, a: `No - pricing is the same across ${loc.borough || 'Greater London'}. There's no callout charge and no location-based surcharge.` },
    { q: 'What happens if you can\'t fix my device?', a: 'You pay nothing at all - no diagnostic fee, no callout charge. That is our No Fix, No Fee guarantee on every visit.' },
    { q: 'How far in advance do I need to book?', a: `Often not far at all - same-day visits in ${loc.name} are common if you call before 2pm, though evenings and weekends can be booked ahead if that suits you better.` },
  ],
];

function variantIndexFor(slug: string): number {
  let sum = 0;
  for (let i = 0; i < slug.length; i++) sum += slug.charCodeAt(i);
  return sum % LOCATION_FAQ_VARIANTS.length;
}

export function getLocationFaqs(location: Location): LocationFAQ[] {
  const variant = LOCATION_FAQ_VARIANTS[variantIndexFor(location.slug)];
  return variant(location);
}
