import { XBOX_CONSOLE_IMAGE } from '@/lib/consoleImages';

export interface Service {
  slug: string;
  title: string;
  shortTitle: string;
  icon: string;
  image: string;
  description: string;
  longDescription: string;
  commonIssues: string[];
  metaTitle: string;
  metaDescription: string;
  // Used to group services in the nav menu — not shown on the service page itself.
  category: string;
  // Optional page-specific FAQs. When present these replace the generic
  // templated FAQs, giving the page unique, snippet-worthy Q&A content.
  faqs?: { q: string; a: string }[];
  // Optional "What to expect" prose block — unique body copy so the page is
  // not a near-duplicate of the shared service template.
  whatToExpect?: string[];
  // Related service slugs. Used to surface relevant repair-advice blog posts
  // and cross-link tightly related pages (e.g. PS5 HDMI ⇄ PlayStation repair).
  relatedServiceSlugs?: string[];
}

export const SERVICE_CATEGORIES = ['Apple & Mac', 'Windows Laptop & PC', 'Consoles & Gaming', 'Data & Security'] as const;

export const services: Service[] = [
  {
    slug: 'macbook-repair-london',
    title: 'MacBook Repair London',
    shortTitle: 'MacBook Repair',
    icon: '💻',
    image: '/images/macbook-pro-unsplash.jpg',
    description: 'Expert MacBook Pro, MacBook Air & iMac repair. Same-day callout across London.',
    longDescription: 'MacBook repair across London, at your home or office. We fix every MacBook model — M1, M2 and M3 MacBook Pro and MacBook Air, plus older Intel MacBooks, iMac and Mac Mini. Most software and hardware faults are diagnosed and repaired on the spot by an Apple-experienced engineer, with no need to visit a shop or post your Mac away.',
    commonIssues: [
      'MacBook not turning on',
      'Liquid / water damage repair',
      'Logic board failure',
      'Keyboard replacement (butterfly & magic)',
      'Charging port not working',
      'MacOS not booting / black screen',
      'Fan noise / overheating',
      'WiFi not connecting',
    ],
    metaTitle: 'MacBook Repair London | Same Day Callout',
    metaDescription: 'Expert MacBook Pro, MacBook Air & iMac repair across London. Same-day home & office visits. No fix, no fee. Call 07378 349222.',
    category: 'Apple & Mac',
    relatedServiceSlugs: ['macbook-screen-repair-london', 'macbook-battery-replacement-london', 'macbook-pro-repair-london'],
    whatToExpect: [
      'Your MacBook repair starts with a free, no-obligation diagnosis. Our engineer comes to your home or office anywhere in Greater London, finds out exactly what is wrong — whether it is a software fault, a failing battery, a cracked screen or a deeper logic-board problem — and gives you a clear, fixed price before any work begins. If it turns out not to be worth repairing, we tell you honestly.',
      'Most everyday MacBook repairs are completed on-site while you watch: battery replacements, keyboard and trackpad faults, RAM and SSD upgrades, macOS reinstalls, virus removal and charging issues. Around seven in ten jobs are finished in your home or office in a single visit, so you usually keep your Mac the same day.',
      'Some repairs are board-level and need a microscope and proper rework equipment — liquid damage, a MacBook that will not power on, or a failed logic board. For these we take the machine to our workshop, keep you updated throughout, and return it fully tested. Wherever possible your data stays exactly where it is; if the storage itself has failed we will always discuss data recovery options with you first.',
      'Every MacBook repair is backed by our 90-day parts-and-labour warranty and our No Fix, No Fee guarantee — if we cannot fix it, you pay nothing at all. There is never a callout charge, and we quote before we start, so the price we agree is the price you pay.',
    ],
    faqs: [
      { q: 'Which MacBook models do you repair?', a: 'All of them. That includes M1, M2 and M3 MacBook Pro and MacBook Air, every Intel-based MacBook Pro, MacBook Air and 12-inch MacBook, plus iMac, Mac Mini and Mac Pro. If it runs macOS, we can work on it.' },
      { q: 'How much does a MacBook repair cost?', a: 'Our labour rate is £100 per hour (minimum one hour) plus any parts needed, and we always quote the full price upfront before we start. A software-only fix with no parts is just the hourly labour; screen, battery and board-level repairs include the part cost, which we confirm with you first. If we cannot fix it, there is no charge.' },
      { q: 'Do you repair my MacBook at my home, or take it away?', a: 'Most repairs — batteries, keyboards, upgrades, software and charging faults — are done on-site in front of you, usually within the hour. Board-level work such as liquid damage or a Mac that will not power on needs our workshop equipment, so we take those away, keep you updated, and return the Mac fully tested.' },
      { q: 'Will I lose my data during a MacBook repair?', a: 'In almost all repairs your data is completely untouched — a battery, screen or keyboard replacement does not affect the storage. If the SSD itself has failed we will tell you before doing anything and talk through data recovery options. We always recommend a backup before any repair where practical.' },
      { q: 'Is it worth repairing a MacBook with liquid damage?', a: 'Often, yes — but it depends. Liquid damage is very repairable if it is dealt with quickly, before corrosion spreads across the logic board. We diagnose the extent of the damage first and give you an honest view on whether a repair makes sense or whether data recovery is the better route. The diagnosis is free.' },
      { q: 'How quickly can you repair my MacBook in London?', a: 'We offer same-day callouts across Greater London — book before 2pm and we can usually visit the same day, including evenings and weekends at no extra charge. On-site repairs are typically finished in a single visit; workshop repairs are turned around as fast as the parts allow, and we keep you posted throughout.' },
    ],
  },
  {
    slug: 'laptop-repair-london',
    title: 'Laptop Repair London',
    shortTitle: 'Laptop Repair',
    icon: '🖥️',
    image: '/images/laptop-repair-service-unsplash.jpg',
    description: 'HP, Dell, Lenovo, Asus, Acer laptop repairs. Home visits across Greater London.',
    longDescription: 'Laptop repair across London, at your home or office. We fix every major brand — Dell XPS, HP Spectre and Pavilion, Lenovo ThinkPad and IdeaPad, Asus, Acer, MSI and more — from cracked screens and dead batteries to motherboard faults and Windows problems. Most repairs are diagnosed and completed on the spot, so there is no shop to visit and no laptop to post away.',
    commonIssues: [
      'Cracked or broken screen',
      'Laptop not starting / power issues',
      'Keyboard spill damage',
      'Slow laptop - speed upgrade',
      'Hard drive / SSD replacement',
      'Battery not charging or holding charge',
      'Windows not booting / blue screen',
      'Overheating and shutting down',
    ],
    metaTitle: 'Laptop Repair London | HP, Dell, Lenovo',
    metaDescription: 'Fast laptop repair across London. HP, Dell, Lenovo, Asus, Acer and more. Home visits available. No fix, no fee. Call 07378 349222.',
    category: 'Windows Laptop & PC',
    relatedServiceSlugs: ['windows-support-london', 'hardware-upgrades-london', 'virus-removal-london'],
    whatToExpect: [
      'Every laptop repair begins with a free diagnosis. Our engineer comes to your home or office anywhere in Greater London, works out exactly what has failed — a screen, a battery, a charging port, a drive or something on the motherboard — and gives you a fixed price before any work starts. If the laptop is not worth repairing, we will tell you straight.',
      'Most laptop repairs are done on-site while you wait: screen replacements, keyboard and battery swaps, SSD and RAM upgrades, and Windows or software fixes. Around seven in ten jobs are finished in a single visit, so in most cases you keep your laptop the same day rather than losing it for a week.',
      'Some faults are board-level — liquid damage, a laptop that will not power on, or a failed charging circuit — and need a microscope and proper rework tools. For those we take the machine to our workshop, keep you updated, and return it fully tested. Your files stay on the drive throughout; if the drive itself has failed we will talk through data recovery before doing anything.',
      'Every laptop repair carries our 90-day parts-and-labour warranty and our No Fix, No Fee guarantee — if we cannot fix it, you pay nothing, and there is never a callout charge. We quote before we start, so the price we agree is the price you pay.',
    ],
    faqs: [
      { q: 'Which laptop brands do you repair?', a: 'All the major ones — Dell, HP, Lenovo, Asus, Acer, MSI, Microsoft Surface, Samsung, Huawei and more, across both Windows laptops and Chromebooks. Whether it is an everyday ultrabook or a gaming laptop, we can diagnose and repair it.' },
      { q: 'How much does a laptop repair cost?', a: 'Our labour rate is £100 per hour (minimum one hour) plus any parts, and we quote the full price upfront before starting. A software-only fix is just the hourly labour; screen, battery, drive and board-level repairs include the part cost, which we confirm with you first. If we cannot fix it, there is no charge.' },
      { q: 'Is it worth replacing a cracked laptop screen?', a: 'Usually, yes. A screen replacement is one of the most common laptop repairs and is far cheaper than a new machine, especially on a laptop that is otherwise healthy. We source the correct panel for your exact model, fit it — often on-site — and back it with our warranty.' },
      { q: 'Will I lose my files during a laptop repair?', a: 'In almost all cases, no. A screen, battery or keyboard repair does not touch your storage. If the hard drive or SSD itself has failed we will tell you before doing anything and go through data recovery options. We always suggest a backup before any repair where possible.' },
      { q: 'Do you repair laptops at my home or take them away?', a: 'Most repairs — screens, batteries, upgrades and software — are completed on-site in front of you, usually within the hour. Board-level work such as liquid damage or a dead motherboard needs our workshop, so we take those away, keep you posted, and return the laptop fully tested.' },
      { q: 'How quickly can you repair my laptop in London?', a: 'We offer same-day callouts across Greater London — book before 2pm and we can usually visit the same day, including evenings and weekends at no extra charge. On-site repairs are typically done in one visit; workshop repairs are turned around as fast as the parts allow.' },
    ],
  },
  {
    slug: 'windows-support-london',
    title: 'Windows Support London',
    shortTitle: 'Windows Support',
    icon: '🪟',
    image: '/images/nikolai-chernichenko-s6uS36SF91Y-unsplash.jpg',
    description: 'Windows PC and laptop troubleshooting - updates, drivers, slow performance and setup. Home visits across London.',
    longDescription: 'Hands-on Windows support across London, at your home or office. From a PC stuck mid-update to driver conflicts, a corrupted profile, a slow machine or setting up a new computer, we fix Windows problems in person rather than talking you through them down the phone. We work across Windows 10 and Windows 11 on all major laptop and desktop brands, and most issues are sorted on the spot in a single visit.',
    commonIssues: [
      'Windows stuck on updates or a repair loop',
      'Blue screen (BSOD) errors',
      'Slow performance after a Windows update',
      'Driver conflicts and device errors',
      'Wi-Fi, printer or Bluetooth setup issues',
      'New PC setup and data transfer',
      'Corrupted user profile or login errors',
      'Windows 10 to Windows 11 upgrade help',
    ],
    metaTitle: 'Windows Support London | PC Troubleshooting',
    metaDescription: 'Windows PC and laptop support across London. Updates, driver issues, slow performance and setup fixed at your door. No fix, no fee. Call 07378 349222.',
    category: 'Windows Laptop & PC',
    relatedServiceSlugs: ['laptop-repair-london', 'virus-removal-london', 'printer-setup-repair-london'],
    whatToExpect: [
      'Windows support starts with a free diagnosis at your home or office. Rather than reading from a script, our engineer sits at the machine, reproduces the problem and finds the real cause — a broken update, a driver conflict, a corrupted profile or something failing in the background — then tells you the fixed price before doing the work.',
      'The vast majority of Windows problems are solved on-site in a single visit: clearing a stuck update or repair loop, fixing blue-screen errors, removing what is slowing the PC down, sorting Wi-Fi, Bluetooth and printer connections, and setting up a new computer with your files and email carried across. You watch it happen and can ask questions as we go.',
      'If we find the slowdown or instability is caused by failing hardware — a dying drive, not enough memory or an overheating fan — we will show you and give you honest options, whether that is a quick upgrade or simply living with it. We never invent work; software problems get a software fix.',
      'All work is backed by our No Fix, No Fee guarantee — if we cannot resolve the issue you pay nothing — and there is never a callout charge. Any parts or upgrades are quoted upfront and carry our 90-day warranty.',
    ],
    faqs: [
      { q: 'What kind of Windows problems do you fix?', a: 'Everything from a PC stuck in an update or repair loop, blue-screen (BSOD) crashes and driver errors, to slow performance, corrupted user profiles, login problems, Wi-Fi and printer setup, and moving everything across to a new computer. If it runs Windows 10 or 11, we can help.' },
      { q: 'How much does Windows support cost?', a: 'It is £100 per hour of labour (minimum one hour), quoted upfront. Most Windows issues are resolved within that first hour. Software support with no parts is simply the labour charge; if any hardware or upgrade is needed we confirm the cost with you before starting. No fix, no fee.' },
      { q: 'Do you fix Windows in person or remotely?', a: 'Both. This callout service is hands-on at your home or office, which is best for anything hardware-related or a new-PC setup. If your problem is purely software, we also offer secure remote support so we can often fix it the same day without a visit — just ask which suits your issue.' },
      { q: 'My PC got slow after a Windows update — can you fix it?', a: 'Yes. A slowdown after an update is usually a driver conflict, a background process, a broken update or a machine that is short on memory or drive space. We diagnose which it is and fix the software side on-site; if it turns out the hardware is the limit, we will show you a clear upgrade option.' },
      { q: 'Can you set up a new Windows PC and move my files over?', a: 'Absolutely — new-PC setup is one of our most common Windows callouts. We get the machine configured, updated and secured, install your programs, and transfer your documents, photos and email from the old computer so you are ready to go before we leave.' },
      { q: 'How soon can you come out for Windows support?', a: 'We offer same-day visits across Greater London — book before 2pm and we can usually come the same day, including evenings and weekends at no extra charge. Most Windows support jobs are completed in that one visit.' },
    ],
  },
  {
    slug: 'printer-setup-repair-london',
    title: 'Printer Setup & Troubleshooting London',
    shortTitle: 'Printer Support',
    icon: '🖨️',
    image: '/images/printer-service-unsplash.jpg',
    description: 'Printer won\'t connect, print or come online? We set up and troubleshoot home and office printers across London.',
    longDescription: 'A printer that shows offline, won\'t connect to Wi-Fi, or simply refuses to print is one of the most common home and office callouts we get - and one of the most frustrating. We set up new printers, fix connection and driver problems, clear stuck print queues, and get wireless and AirPrint printing working again from Windows PCs, Macs, iPhones and iPads, all at your home or office.',
    commonIssues: [
      'Printer shows "offline" or won\'t come online',
      'Printer won\'t connect to Wi-Fi',
      'Documents stuck in the print queue',
      'New printer setup and driver installation',
      'Printer not detected after a Windows update',
      'Wireless / AirPrint printing from Mac, iPhone or iPad',
      'Scan to computer or email not working',
      'Sharing one printer across several devices',
    ],
    metaTitle: 'Printer Setup & Repair London | Home & Office',
    metaDescription: 'Printer setup and troubleshooting across London. Offline errors, Wi-Fi connection, driver and print-queue problems fixed at your door on Mac and PC. Call 07378 349222.',
    category: 'Windows Laptop & PC',
    relatedServiceSlugs: ['windows-support-london', 'home-office-networking-london', 'laptop-repair-london'],
    whatToExpect: [
      'Printer support starts with a free diagnosis at your home or office. Our engineer finds out why the printer will not play — an offline status, a dropped Wi-Fi connection, a missing or wrong driver, a stuck queue or a setup that was never finished — and gives you a fixed price before any work, so there are no surprises.',
      'Almost every printer problem is solved on-site in a single visit. We reconnect the printer to your network, install the correct drivers on your Windows PCs and Macs, clear jammed print queues, and get wireless and AirPrint printing working from iPhones and iPads too. You will see it print a test page before we leave.',
      'We support all the main brands — HP, Canon, Epson, Brother, Samsung and more — across inkjet, laser and all-in-one models, and we can set one printer up to be shared across several computers and phones in the house or office. Scan-to-computer and scan-to-email are included where your printer supports them.',
      'Everything is covered by our No Fix, No Fee guarantee — if we cannot get your printer working, there is no charge — and there is never a callout fee. We quote before we start and stay until it is genuinely working, not just plugged in.',
    ],
    faqs: [
      { q: 'Why does my printer say it is offline when it is switched on?', a: 'An "offline" status almost always means the computer has lost its connection to the printer — often after a Wi-Fi change, a router restart or a Windows update reset the settings. It rarely means the printer is broken. We reconnect it and set it so it stays online, usually within the first visit.' },
      { q: 'Can you get my printer working over Wi-Fi?', a: 'Yes — wireless printing is one of our most common callouts. We connect the printer to your network properly, install the right drivers on each Mac and PC, and set up AirPrint so you can print straight from an iPhone or iPad as well. We test it on every device before we go.' },
      { q: 'Which printer brands do you support?', a: 'All the main ones — HP, Canon, Epson, Brother, Samsung, Lexmark and others — across inkjet, laser and all-in-one printers, on both Windows and Mac. Whether it is a home printer or a busy office machine, we can set it up or troubleshoot it.' },
      { q: 'How much does printer support cost?', a: 'It is our standard £100 per hour of labour (minimum one hour), quoted upfront. The large majority of printer setup and troubleshooting jobs are finished well within the hour. If we cannot get it working, you pay nothing under our No Fix, No Fee guarantee.' },
      { q: 'Can you set one printer up for several computers?', a: 'Yes. We can configure a single printer so everyone in the home or office can print to it wirelessly, from Windows PCs, Macs, phones and tablets, and set up scan-to-computer or scan-to-email where the printer supports it.' },
      { q: 'How quickly can you come out?', a: 'We offer same-day visits across Greater London — book before 2pm and we can usually come the same day, evenings and weekends included, at no extra charge. Printer jobs are almost always sorted in that single visit.' },
    ],
  },
  {
    slug: 'hardware-upgrades-london',
    title: 'Hardware Upgrades London',
    shortTitle: 'Hardware Upgrades',
    icon: '⚙️',
    image: '/images/nathan-anderson-KHSPGJ3zP0M-unsplash.jpg',
    description: 'RAM and SSD upgrades for laptops, desktops and older Macs. Faster performance fitted at your home.',
    longDescription: 'Hardware upgrades across London, fitted at your home or office. A slow computer often just needs more memory or a faster drive rather than a full repair — and it is one of the most cost-effective ways to get years more life out of a machine. We fit RAM upgrades and SSD replacements in laptops, desktop PCs and older Mac models with upgradeable components, cloning your existing data across so nothing is lost and your machine starts up exactly as before, only faster.',
    commonIssues: [
      'Laptop or PC feels slow with several programs open',
      'Old hard drive holding back an otherwise healthy machine',
      'Not enough RAM for video calls, editing or gaming',
      'Older iMac or Mac Mini with upgradeable memory or storage',
      'Running out of storage space',
      'Upgrading from a hard drive to an SSD for a faster boot',
      'Adding extra RAM to an existing desktop',
      'Data migration to a new drive without losing files',
    ],
    metaTitle: 'Hardware Upgrades London | RAM & SSD',
    metaDescription: 'RAM and SSD upgrades across London for laptops, desktops and older Macs. Faster performance, more storage, data migrated safely. Call 07378 349222.',
    category: 'Windows Laptop & PC',
    relatedServiceSlugs: ['laptop-repair-london', 'data-recovery-london', 'macbook-repair-london'],
    whatToExpect: [
      'Every hardware upgrade starts with an honest check. Our engineer confirms what your machine actually takes — how much RAM it supports, whether the drive can be swapped, and whether an upgrade will genuinely make a difference — and gives you a fixed price for parts and fitting before anything is opened up. If an upgrade would not help, we will say so.',
      'The single biggest speed jump on most older computers is moving from a hard drive to an SSD. We clone your existing Windows or macOS setup across to the new drive so everything — your programs, files and settings — comes back exactly as it was, just far faster to boot and open. Adding RAM on top helps machines that struggle with lots of tabs, video calls or editing.',
      'Most upgrades are done on-site in a single visit: laptops, desktop PCs and older iMac and Mac Mini models with upgradeable memory or storage. We handle the data migration for you, so you are not left copying files across by hand or setting a machine up from scratch.',
      'Upgrades are quoted upfront with no callout charge, and the parts and workmanship are covered by our 90-day warranty. Because it is planned work rather than a fault, you get faster performance without the cost or hassle of replacing the whole computer.',
    ],
    faqs: [
      { q: 'Will upgrading to an SSD really make my computer faster?', a: 'Almost always, dramatically so. On an older machine still running a traditional hard drive, swapping to an SSD is the single biggest speed improvement you can make — boot times, opening programs and general responsiveness all transform. It is the first upgrade we recommend for a computer that feels sluggish.' },
      { q: 'Will I lose my files or have to reinstall everything?', a: 'No. We clone your existing drive across to the new SSD, so Windows or macOS, your programs, files and settings all come back exactly as they were — just faster. There is no reinstalling and no setting the machine up from scratch.' },
      { q: 'Can my laptop or Mac actually be upgraded?', a: 'It depends on the model. Many laptops, most desktop PCs, and older iMac and Mac Mini models have upgradeable RAM or storage; some newer, thinner machines and Apple Silicon Macs have memory and storage soldered in and cannot be changed. We confirm exactly what yours supports before quoting, so you never pay for an upgrade that will not fit.' },
      { q: 'How much do RAM and SSD upgrades cost?', a: 'You pay our £100 per hour fitting labour (usually well within the hour) plus the cost of the RAM or SSD itself, both quoted upfront. It is a fraction of the price of a new computer and typically buys you several more years of use. No fix, no fee still applies if we cannot complete it.' },
      { q: 'How much RAM or storage should I add?', a: 'It depends on how you use the machine — we will advise based on that. As a rule, 16GB of RAM is a comfortable target for everyday use and video calls, with more for heavy editing or gaming, and we size the SSD to comfortably fit what you already store with room to grow.' },
      { q: 'Can you fit the upgrade at my home?', a: 'Yes — most RAM and SSD upgrades are fitted on-site in a single visit across Greater London, including the data migration. Book before 2pm and we can usually come the same day, evenings and weekends included, with no callout charge.' },
    ],
  },
  {
    slug: 'home-office-networking-london',
    title: 'Home & Office Networking London',
    shortTitle: 'Networking Support',
    icon: '📶',
    image: '/images/jay-wennington-3xf07twcxsY-unsplash.jpg',
    description: 'Wi-Fi, router and network setup for homes and small offices. Faster, more reliable connections across London.',
    longDescription: 'Weak Wi-Fi, dropped connections and devices that will not see each other usually come down to router placement, configuration or ageing equipment. We set up and troubleshoot home and small office networks, including routers, mesh Wi-Fi, extenders, printers and shared drives.',
    commonIssues: [
      'Wi-Fi not reaching every room',
      'Router needs setting up or replacing',
      'Devices dropping off the network randomly',
      'Printer or shared drive not visible on the network',
      'Mesh Wi-Fi system setup and optimisation',
      'Slow internet despite a fast broadband plan',
      'Setting up a new router after a broadband switch',
      'Securing a home or office network',
    ],
    metaTitle: 'Networking & Wi-Fi Setup London',
    metaDescription: 'Home and office network setup across London. Wi-Fi, routers, mesh systems and shared drives fixed at your door. No fix, no fee. Call 07378 349222.',
    category: 'Windows Laptop & PC',
  },
  {
    slug: 'data-recovery-london',
    title: 'Data Recovery London',
    shortTitle: 'Data Recovery',
    icon: '💾',
    image: '/images/data-recovery-service-unsplash.jpg',
    description: 'Recover lost files from crashed drives, deleted partitions, and formatted disks.',
    longDescription: 'Lost important files? We recover data from failed hard drives, SSDs, USB drives, SD cards and RAID arrays. We handle Mac APFS, Windows NTFS, formatted drives and accidental deletions.',
    commonIssues: [
      'Accidental file deletion',
      'Hard drive clicking / not detected',
      'Formatted or corrupted drive',
      'MacBook SSD failure after liquid damage',
      'Windows drive partition loss',
      'USB or external drive not showing',
      'RAID / NAS data recovery',
      'Photos and videos from memory cards',
    ],
    metaTitle: 'Data Recovery London | Hard Drive & SSD',
    metaDescription: 'Professional data recovery across London. Retrieve lost files from crashed drives, formatted disks and failed SSDs. Call 07378 349222.',
    category: 'Data & Security',
  },
  {
    slug: 'gaming-pc-repair-london',
    title: 'Gaming PC Repair London',
    shortTitle: 'Gaming PC Repair',
    icon: '🎮',
    image: '/images/gaming-pc-service-unsplash.jpg',
    description: 'Gaming desktop and laptop repair. BIOS tuning, GPU issues, performance optimisation.',
    longDescription: 'We fix gaming PCs, desktops and gaming laptops. Whether it\'s an Alienware, ASUS ROG, Razer Blade, MSI or custom-built PC - we diagnose and repair GPU faults, PSU failures, overheating, and Windows gaming issues.',
    commonIssues: [
      'GPU crashing or no display',
      'PC shutting down during games',
      'BIOS not posting / black screen',
      'PSU fan noise or failure',
      'RAM errors and crashes',
      'Overheating - thermal paste & cooling',
      'Windows game optimisation',
      'Custom PC build and upgrades',
    ],
    metaTitle: 'Gaming PC Repair London | Desktop & Laptop',
    metaDescription: 'Gaming PC and laptop repair across London. GPU, PSU, overheating fixes. Alienware, ASUS ROG, MSI, custom builds. Call 07378 349222.',
    category: 'Windows Laptop & PC',
  },
  {
    slug: 'virus-removal-london',
    title: 'Virus & Malware Removal London',
    shortTitle: 'Virus Removal',
    icon: '🛡️',
    image: '/images/virus-removal-service-unsplash.jpg',
    description: 'Remove viruses, ransomware, spyware and malware from Mac and PC. Same-day service.',
    longDescription: 'Ransomware, spyware, adware and browser hijackers can destroy your data and compromise your privacy. We fully clean your Mac or PC, remove all malware, and set up proper security to prevent reinfection.',
    commonIssues: [
      'Pop-up ads and browser redirects',
      'Ransomware / files encrypted',
      'PC running very slowly',
      'Fake virus warning pop-ups',
      'Webcam or microphone spied on',
      'Suspicious programs starting automatically',
      'Email account hacked via PC',
      'Mac infected with adware',
    ],
    metaTitle: 'Virus Removal London | Malware & Ransomware',
    metaDescription: 'Same-day virus and malware removal across London. Mac and PC. Ransomware, spyware, adware cleaned. No fix, no fee. Call 07378 349222.',
    category: 'Data & Security',
  },
  {
    slug: 'macbook-screen-repair-london',
    title: 'MacBook Screen Repair London',
    shortTitle: 'Screen Repair',
    icon: '🖱️',
    image: '/images/macbook-screen-repair-service-unsplash.jpg',
    description: 'MacBook Pro and MacBook Air screen replacement. Cracked, flickering or dead displays fixed same day.',
    longDescription: 'We replace cracked, flickering, dead, or dim MacBook screens using quality replacement panels. We cover MacBook Pro 13", 14", 15", 16" and MacBook Air 13", 15" - including Retina and Liquid Retina XDR displays.',
    commonIssues: [
      'Cracked MacBook Pro screen',
      'MacBook Air screen broken after drop',
      'Flickering or lines on display',
      'Black screen - backlight failure',
      'MacBook screen damage from liquid',
      'Dim screen - inverter fault',
      'Dead pixels or colour distortion',
      'Screen hinge broken',
    ],
    metaTitle: 'MacBook Screen Repair London | Same Day',
    metaDescription: 'MacBook Pro and MacBook Air screen replacement across London. Cracked, flickering or dead displays. Same-day home visit. Call 07378 349222.',
    category: 'Apple & Mac',
  },
  {
    slug: 'macbook-battery-replacement-london',
    title: 'MacBook Battery Replacement London',
    shortTitle: 'Battery Replacement',
    icon: '🔋',
    image: '/images/zoshua-colah-HEIeRujWthM-unsplash.jpg',
    description: 'MacBook battery not holding charge? We replace MacBook Pro and Air batteries at your door.',
    longDescription: 'A failing MacBook battery drains fast, shuts down unexpectedly or shows "Service Recommended". We replace genuine-spec batteries on all MacBook Pro and MacBook Air models, including glued-in batteries on newer Retina models.',
    commonIssues: [
      'MacBook dies within an hour',
      '"Battery Service Recommended" warning',
      'MacBook only works when plugged in',
      'Battery swollen - urgent safety issue',
      'MacBook shutting off at 20–30%',
      'Cycle count over 1000',
      'MacBook discharging overnight',
      'macOS showing reduced battery capacity',
    ],
    metaTitle: 'MacBook Battery Replacement London',
    metaDescription: 'MacBook Pro and Air battery replacement across London. Home visits, genuine-spec parts. Fast turnaround. No fix, no fee. Call 07378 349222.',
    category: 'Apple & Mac',
  },
  {
    slug: 'water-damage-repair-london',
    title: 'Water Damage Repair London',
    shortTitle: 'Water Damage Repair',
    icon: '💧',
    image: '/images/water-damage-service-unsplash.jpg',
    description: 'MacBook or laptop liquid damage? Act fast - we provide same-day emergency callout.',
    longDescription: 'Spilt water, coffee or juice on your MacBook or laptop? Act immediately - every minute counts with liquid damage. Do not turn it on. Call us now for a same-day emergency visit.',
    commonIssues: [
      'MacBook wet - spilled water or coffee',
      'Keyboard keys not working after spill',
      'MacBook won\'t turn on after liquid damage',
      'Trackpad not responding after water',
      'Laptop screen damaged by liquid',
      'Corrosion on logic board',
      'USB or charging port corroded',
      'Battery short-circuit from water',
    ],
    metaTitle: 'Water Damage Repair London | Mac & Laptop',
    metaDescription: 'Emergency liquid damage repair across London. MacBook and laptop spill recovery. Same-day callout. Do not turn it on - call 07378 349222.',
    category: 'Data & Security',
  },
  {
    slug: 'playstation-repair-london',
    title: 'PlayStation Repair London',
    shortTitle: 'PlayStation Repair',
    icon: '🎮',
    image: '/images/playstation-service-unsplash.jpg',
    description: 'PS5 & PS4 repair at your home. HDMI port, overheating, disc drive & controller faults fixed.',
    longDescription: 'PlayStation not working? We repair PS5 and PS4 consoles at your home or office across Greater London. From the common PS5 HDMI port failure to disc drive faults, overheating shutdowns and controller issues — our engineers diagnose and fix your console on-site, so you are back gaming the same day.',
    commonIssues: [
      'PS5 HDMI port broken — no picture',
      'PS4 / PS5 overheating and shutting down',
      'Disc drive not reading or ejecting discs',
      'PlayStation not turning on',
      'Blue light of death (BLOD)',
      'DualSense / DualShock controller drift',
      'PS5 loud fan noise',
      'PlayStation connected but no display on TV',
      'PSN account issues / system software',
      'USB port broken on controller or console',
    ],
    metaTitle: 'PlayStation Repair London | PS5 & PS4',
    metaDescription: 'PS5 and PS4 repair across Greater London. HDMI port, overheating, disc drive, controller faults fixed at your door. No fix, no fee. Call 07378 349222.',
    category: 'Consoles & Gaming',
    relatedServiceSlugs: ['ps5-hdmi-port-repair-london', 'gaming-console-repair-london'],
    whatToExpect: [
      'Your engineer starts with a full diagnosis so you know exactly what has failed before any work or cost is agreed — a "no picture" fault can be a damaged HDMI port, a failed HDMI encoder chip, or a cable/TV issue, and they are not all the same repair.',
      'Straightforward jobs — controller drift, cleaning a clogged fan, reseating a disc drive, software and storage problems — are usually handled on-site in front of you the same day.',
      'Board-level work such as HDMI port replacement or an overheating console that needs a full strip-down, re-paste and reflow is done at our workshop on proper soldering equipment, then returned to you. We always confirm this and quote before anything is taken away.',
      'Every PlayStation repair is backed by our 90-day parts-and-labour warranty, and if we cannot fix it you pay nothing.',
    ],
    faqs: [
      { q: 'My PS5 turns on but there is no picture on the TV — what is wrong?', a: 'This is almost always the HDMI port or the console\'s HDMI output, not your TV. If the console powers on with a light and fan noise but the screen shows "No Signal", the port is the most common cause — especially if the console was knocked or moved with the cable still plugged in. We test the port, cable and output to confirm before quoting. See our dedicated PS5 HDMI port repair page for this specific fault.' },
      { q: 'Can you fix a broken PS5 HDMI port, or do I need a new console?', a: 'In most cases we can replace the HDMI port — you do not need to buy a new console. The damaged port is desoldered and a new one fitted at our workshop under a microscope. This is far cheaper than a replacement PS5 and keeps all your games, saves and account intact.' },
      { q: 'Will I lose my games or save data if you repair my PlayStation?', a: 'No. Port repairs, fan cleans, disc-drive and controller fixes do not touch the internal storage, so your installed games, saves and PSN account are untouched. If a repair ever risked data we would tell you first.' },
      { q: 'How long does a PlayStation repair take?', a: 'On-site jobs like controller drift, fan cleaning or software issues are usually done the same day within an hour. HDMI port replacement and full overheating strip-downs are workshop repairs, typically returned within a few days depending on parts.' },
      { q: 'Why does my PS5 keep overheating and shutting down?', a: 'Usually dust build-up in the fan and heatsink, or dried-out thermal paste, causing the console to hit its safety cut-off. We strip the console down, clean it fully, and re-paste the APU so it runs cool and quiet again.' },
      { q: 'Do you repair PS4 as well as PS5?', a: 'Yes — we repair PS5, PS5 Slim, PS4, PS4 Pro and PS4 Slim, including HDMI ports, disc drives, overheating, power faults and controllers.' },
    ],
  },
  {
    slug: 'gaming-console-repair-london',
    title: 'Gaming Console Repair London',
    shortTitle: 'Console Repair',
    icon: '🕹️',
    image: XBOX_CONSOLE_IMAGE,
    description: 'Xbox, Nintendo Switch and general console repairs at home across Greater London.',
    longDescription: 'We repair gaming consoles including Xbox Series X, Xbox Series S, Xbox One, Nintendo Switch, and other popular systems across Greater London. From HDMI faults and charging issues to overheating and storage problems, we diagnose your console at home or office and explain the fix clearly before any work starts.',
    commonIssues: [
      'Xbox HDMI port damaged or no display',
      'Nintendo Switch not charging',
      'Console overheating and shutting down',
      'Broken USB-C or power ports',
      'Fan noise and dust-related heat issues',
      'Controller pairing or connection faults',
      'Storage errors and corrupt updates',
      'Disc drive or cartridge reader faults',
    ],
    metaTitle: 'Console Repair London | Xbox & Switch',
    metaDescription: 'Gaming console repair across London for Xbox, Nintendo Switch and more. HDMI, charging, overheating, storage and port faults fixed at your door.',
    category: 'Consoles & Gaming',
    relatedServiceSlugs: ['playstation-repair-london', 'ps5-hdmi-port-repair-london'],
    whatToExpect: [
      'We repair Xbox Series X, Series S, Xbox One, Nintendo Switch, Switch Lite and Switch OLED — so the first step is a proper diagnosis to confirm whether the fault is a port, the power system, thermals, or storage.',
      'Common quick fixes — a Switch that will not charge because of a worn USB-C port, a dust-clogged fan, controller pairing faults, or a corrupt update — are often sorted on-site the same day.',
      'HDMI port replacement, board-level power faults and full overheating strip-downs are workshop repairs on proper micro-soldering equipment. We explain which category your console falls into, and quote, before any work begins.',
      'All console repairs carry our 90-day parts-and-labour warranty, and our No Fix, No Fee guarantee means you pay nothing if we can\'t repair it.',
    ],
    faqs: [
      { q: 'My Xbox Series X shows no display — is it the HDMI port or the console?', a: 'Both are possible. A bent or damaged HDMI port is common after the console has been moved with the cable still connected, but a "no display" fault can also be the internal HDMI chip or the retimer. We test the port and output to pinpoint it before quoting, so you are not paying for the wrong repair.' },
      { q: 'Why won\'t my Nintendo Switch charge?', a: 'The most common cause is a worn or damaged USB-C charging port, especially on consoles that are docked and undocked a lot. We can replace the USB-C port so it charges reliably again. We always test with a known-good charger first to rule out a faulty cable or adapter.' },
      { q: 'Can you fix an Xbox or Switch HDMI port, or the Switch dock?', a: 'Yes. We replace damaged HDMI ports on Xbox consoles at our workshop under a microscope, and diagnose Switch dock and video-output faults. This is far cheaper than replacing the console and keeps your games and account intact.' },
      { q: 'My console keeps overheating and shutting down — can you fix that?', a: 'Yes. Overheating is usually dust build-up and dried thermal paste making the console hit its safety cut-off. We strip it down, clean the fan and heatsink, and re-paste the processor so it runs cool and quiet again.' },
      { q: 'Do you repair PlayStation too?', a: 'Yes — we have a dedicated PlayStation repair service for PS5 and PS4, including the common PS5 HDMI port failure. Just let us know your console when you book.' },
    ],
  },
  {
    slug: 'macbook-pro-repair-london',
    title: 'MacBook Pro Repair London',
    shortTitle: 'MacBook Pro Repair',
    icon: '💻',
    image: '/images/macbook-pro-unsplash.jpg',
    description: 'Specialist MacBook Pro M1, M2, M3 and Intel logic board and screen repair.',
    longDescription: 'We offer hyper-specialised repairs for MacBook Pro 13", 14", 15" and 16" models. Whether you have an older Intel core model with a failing battery, or a brand new M3 Max with a cracked Liquid Retina XDR display, our engineers bring the Apple-certified workshop directly to your home.',
    commonIssues: [
      'M1/M2/M3 MacBook Pro Screen Replacement',
      'MacBook Pro Touch Bar not responding',
      'Logic Board short circuit repair',
      'Battery swollen or Service Recommended',
      'MacBook Pro liquid damage recovery',
      'Overheating and loud fan noise',
    ],
    metaTitle: 'MacBook Pro Repair London | Same Day',
    metaDescription: 'Specialist MacBook Pro repair across London. M1, M2, M3 and Intel models. Screen replacement, battery, liquid damage fixed at your door. No fix, no fee.',
    category: 'Apple & Mac',
  },
  {
    slug: 'macbook-air-repair-london',
    title: 'MacBook Air Repair London',
    shortTitle: 'MacBook Air Repair',
    icon: '💻',
    image: '/images/albert-vinas-F3t-AzyTbyU-unsplash.jpg',
    description: 'Expert MacBook Air repair. M1, M2, M3 and Intel models fixed at your home.',
    longDescription: 'MacBook Air laptops are ultra-thin and highly susceptible to screen cracking and liquid damage. We provide rapid same-day callouts to replace MacBook Air 13" and 15" screens, recover corroded logic boards from coffee spills, and replace exhausted batteries.',
    commonIssues: [
      'MacBook Air M1/M2 screen cracked',
      'Liquid spilled on MacBook Air keyboard',
      'MacBook Air not turning on',
      'Battery draining unusually fast',
      'Trackpad not clicking or responding',
      'USB-C charging ports loose or failing',
    ],
    metaTitle: 'MacBook Air Repair London | Same Day',
    metaDescription: 'Expert MacBook Air repair in London. M1, M2, M3 screen replacement, battery upgrades and liquid damage repair. We come to you. Call 07378 349222.',
    category: 'Apple & Mac',
  },
  {
    slug: 'ps5-hdmi-port-repair-london',
    title: 'PS5 HDMI Port Repair London',
    shortTitle: 'PS5 HDMI Repair',
    icon: '🎮',
    image: '/images/playstation-service-unsplash.jpg',
    description: 'PS5 turning on but no signal? We replace broken PS5 HDMI ports with a full warranty.',
    longDescription: 'The most common PlayStation 5 fault is a broken or loose HDMI port. If your PS5 powers on with a white light but shows "No Signal" on your TV, the port is likely damaged internally — often after the console was moved with the cable still plugged in. We desolder the damaged port and micro-solder a new one onto your PS5 board under a microscope at our workshop, then return your console fully tested. Diagnosis is free and we quote before any work begins.',
    commonIssues: [
      'PS5 No Signal on TV',
      'HDMI port visibly bent or broken',
      'Screen flickering or dropping out',
      'PS5 powers on but black screen',
      'Pins pushed back inside the port',
      'Requires wiggling the cable to get picture',
    ],
    metaTitle: 'PS5 HDMI Port Repair London | No Signal Fix',
    metaDescription: 'PS5 HDMI port repair across London. No signal or broken port? We micro-solder a new HDMI port and return your console fully tested. No fix, no fee. Call 07378 349222.',
    category: 'Consoles & Gaming',
    relatedServiceSlugs: ['playstation-repair-london', 'gaming-console-repair-london'],
    whatToExpect: [
      'First we confirm the fault is really the HDMI port. A PS5 that lights up but shows "No Signal" can be a damaged port, a failed HDMI encoder (retimer) chip, or simply a bad cable or TV input — and each needs a different fix. Diagnosis is free and you get a clear answer before any cost is agreed.',
      'HDMI port replacement is precision board-level work: the damaged port is desoldered and a new one micro-soldered onto the PS5 mainboard under a microscope. This is done at our workshop on proper rework equipment, not on a kitchen table, so the joint is reliable and lasts.',
      'Your games, saves and PSN account are on the internal storage and are completely unaffected — an HDMI repair does not touch your data.',
      'The finished console is tested on a screen before it comes back to you, and the repair is covered by our 90-day parts-and-labour warranty. If we can\'t fix it, you pay nothing.',
    ],
    faqs: [
      { q: 'How do I know if it\'s the HDMI port and not my TV?', a: 'Try a different HDMI cable and a different input or TV first. If the PS5 still shows "No Signal" everywhere but powers on with a light and fan noise, the fault is almost certainly the console\'s HDMI port or output rather than the TV. We confirm this with a free diagnosis before quoting.' },
      { q: 'Can a broken PS5 HDMI port actually be repaired?', a: 'Yes. In most cases the physical port is replaced — we desolder the damaged one and micro-solder a new port onto the mainboard under a microscope. You do not need a new console, and all your games and saves are kept. Occasionally the fault is the HDMI encoder chip rather than the port; we tell you which it is after diagnosis.' },
      { q: 'How much does a PS5 HDMI port repair cost?', a: 'It is our £100 hourly labour plus the replacement port, quoted upfront before any work starts. It is a fraction of the cost of a new PS5, and there is no charge at all if we cannot fix it.' },
      { q: 'Will I lose my games or saves?', a: 'No. The HDMI port is separate from the internal SSD, so your installed games, saves and PSN account are completely untouched by the repair.' },
      { q: 'How long does the repair take?', a: 'HDMI port replacement is board-level workshop work, usually turned around within a few days depending on parts. We keep you updated and only return the console once it is tested on a screen.' },
      { q: 'What causes the PS5 HDMI port to break in the first place?', a: 'The most common cause is knocking or moving the console while the HDMI cable is plugged in, which levers the port and cracks its solder joints or bends the pins. Keeping the console on a stable surface and not tugging the cable helps prevent it.' },
    ],
  }
];

export function getService(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}
