import { XBOX_CONSOLE_IMAGE } from '@/lib/consoleImages';

export interface Service {
  slug: string;
  title: string;
  shortTitle: string;
  icon: string;
  image: string;
  description: string;
  longDescription: string;
  commonIssues: string[];
  metaTitle: string;
  metaDescription: string;
  // Used to group services in the nav menu — not shown on the service page itself.
  category: string;
}

export const SERVICE_CATEGORIES = ['Apple & Mac', 'Windows Laptop & PC', 'Consoles & Gaming', 'Data & Security'] as const;

export const services: Service[] = [
  {
    slug: 'macbook-repair-london',
    title: 'MacBook Repair London',
    shortTitle: 'MacBook Repair',
    icon: '💻',
    image: '/images/macbook-pro-unsplash.jpg',
    description: 'Expert MacBook Pro, MacBook Air & iMac repair. Same-day callout across London.',
    longDescription: 'We specialise in all MacBook models including M1, M2, M3 MacBook Pro and MacBook Air, plus iMac and Mac Mini. Our Apple-experienced technicians come to your home or office - no need to visit a shop.',
    commonIssues: [
      'MacBook not turning on',
      'Liquid / water damage repair',
      'Logic board failure',
      'Keyboard replacement (butterfly & magic)',
      'Charging port not working',
      'MacOS not booting / black screen',
      'Fan noise / overheating',
      'WiFi not connecting',
    ],
    metaTitle: 'MacBook Repair London | Same Day Callout',
    metaDescription: 'Expert MacBook Pro, MacBook Air & iMac repair across London. Same-day home & office visits. No fix, no fee. Call 07378 349222.',
    category: 'Apple & Mac',
  },
  {
    slug: 'laptop-repair-london',
    title: 'Laptop Repair London',
    shortTitle: 'Laptop Repair',
    icon: '🖥️',
    image: '/images/laptop-repair-service-unsplash.jpg',
    description: 'HP, Dell, Lenovo, Asus, Acer laptop repairs. Home visits across Greater London.',
    longDescription: 'From screen replacements to motherboard repairs, we fix all major laptop brands at your home or office. Our engineers handle Dell XPS, HP Spectre, Lenovo ThinkPad, Asus ROG, Acer Aspire and more.',
    commonIssues: [
      'Cracked or broken screen',
      'Laptop not starting / power issues',
      'Keyboard spill damage',
      'Slow laptop - speed upgrade',
      'Hard drive / SSD replacement',
      'Battery not charging or holding charge',
      'Windows not booting / blue screen',
      'Overheating and shutting down',
    ],
    metaTitle: 'Laptop Repair London | HP, Dell, Lenovo',
    metaDescription: 'Fast laptop repair across London. HP, Dell, Lenovo, Asus, Acer and more. Home visits available. No fix, no fee. Call 07378 349222.',
    category: 'Windows Laptop & PC',
  },
  {
    slug: 'windows-support-london',
    title: 'Windows Support London',
    shortTitle: 'Windows Support',
    icon: '🪟',
    image: '/images/nikolai-chernichenko-s6uS36SF91Y-unsplash.jpg',
    description: 'Windows PC and laptop troubleshooting - updates, drivers, slow performance and setup. Home visits across London.',
    longDescription: 'From a laptop stuck mid-update to driver conflicts, a corrupted profile, or setting up a new PC, we provide hands-on Windows support at your home or office. We work across Windows 10 and Windows 11 on all major laptop and desktop brands.',
    commonIssues: [
      'Windows stuck on updates or a repair loop',
      'Blue screen (BSOD) errors',
      'Slow performance after a Windows update',
      'Driver conflicts and device errors',
      'Wi-Fi, printer or Bluetooth setup issues',
      'New PC setup and data transfer',
      'Corrupted user profile or login errors',
      'Windows 10 to Windows 11 upgrade help',
    ],
    metaTitle: 'Windows Support London | PC Troubleshooting',
    metaDescription: 'Windows PC and laptop support across London. Updates, driver issues, slow performance and setup fixed at your door. No fix, no fee. Call 07378 349222.',
    category: 'Windows Laptop & PC',
  },
  {
    slug: 'hardware-upgrades-london',
    title: 'Hardware Upgrades London',
    shortTitle: 'Hardware Upgrades',
    icon: '⚙️',
    image: '/images/nathan-anderson-KHSPGJ3zP0M-unsplash.jpg',
    description: 'RAM and SSD upgrades for laptops, desktops and older Macs. Faster performance fitted at your home.',
    longDescription: 'A slow computer often just needs more memory or a faster drive rather than a full repair. We fit RAM upgrades and SSD replacements in laptops, desktop PCs, and older Mac models with upgradeable components, cloning your existing data across so nothing is lost.',
    commonIssues: [
      'Laptop or PC feels slow with several programs open',
      'Old hard drive holding back an otherwise healthy machine',
      'Not enough RAM for video calls, editing or gaming',
      'Older iMac or Mac Mini with upgradeable memory or storage',
      'Running out of storage space',
      'Upgrading from a hard drive to an SSD for a faster boot',
      'Adding extra RAM to an existing desktop',
      'Data migration to a new drive without losing files',
    ],
    metaTitle: 'Hardware Upgrades London | RAM & SSD',
    metaDescription: 'RAM and SSD upgrades across London for laptops, desktops and older Macs. Faster performance, more storage, data migrated safely. Call 07378 349222.',
    category: 'Windows Laptop & PC',
  },
  {
    slug: 'home-office-networking-london',
    title: 'Home & Office Networking London',
    shortTitle: 'Networking Support',
    icon: '📶',
    image: '/images/jay-wennington-3xf07twcxsY-unsplash.jpg',
    description: 'Wi-Fi, router and network setup for homes and small offices. Faster, more reliable connections across London.',
    longDescription: 'Weak Wi-Fi, dropped connections and devices that will not see each other usually come down to router placement, configuration or ageing equipment. We set up and troubleshoot home and small office networks, including routers, mesh Wi-Fi, extenders, printers and shared drives.',
    commonIssues: [
      'Wi-Fi not reaching every room',
      'Router needs setting up or replacing',
      'Devices dropping off the network randomly',
      'Printer or shared drive not visible on the network',
      'Mesh Wi-Fi system setup and optimisation',
      'Slow internet despite a fast broadband plan',
      'Setting up a new router after a broadband switch',
      'Securing a home or office network',
    ],
    metaTitle: 'Networking & Wi-Fi Setup London',
    metaDescription: 'Home and office network setup across London. Wi-Fi, routers, mesh systems and shared drives fixed at your door. No fix, no fee. Call 07378 349222.',
    category: 'Windows Laptop & PC',
  },
  {
    slug: 'data-recovery-london',
    title: 'Data Recovery London',
    shortTitle: 'Data Recovery',
    icon: '💾',
    image: '/images/data-recovery-service-unsplash.jpg',
    description: 'Recover lost files from crashed drives, deleted partitions, and formatted disks.',
    longDescription: 'Lost important files? We recover data from failed hard drives, SSDs, USB drives, SD cards and RAID arrays. We handle Mac APFS, Windows NTFS, formatted drives and accidental deletions.',
    commonIssues: [
      'Accidental file deletion',
      'Hard drive clicking / not detected',
      'Formatted or corrupted drive',
      'MacBook SSD failure after liquid damage',
      'Windows drive partition loss',
      'USB or external drive not showing',
      'RAID / NAS data recovery',
      'Photos and videos from memory cards',
    ],
    metaTitle: 'Data Recovery London | Hard Drive & SSD',
    metaDescription: 'Professional data recovery across London. Retrieve lost files from crashed drives, formatted disks and failed SSDs. Call 07378 349222.',
    category: 'Data & Security',
  },
  {
    slug: 'gaming-pc-repair-london',
    title: 'Gaming PC Repair London',
    shortTitle: 'Gaming PC Repair',
    icon: '🎮',
    image: '/images/gaming-pc-service-unsplash.jpg',
    description: 'Gaming desktop and laptop repair. BIOS tuning, GPU issues, performance optimisation.',
    longDescription: 'We fix gaming PCs, desktops and gaming laptops. Whether it\'s an Alienware, ASUS ROG, Razer Blade, MSI or custom-built PC - we diagnose and repair GPU faults, PSU failures, overheating, and Windows gaming issues.',
    commonIssues: [
      'GPU crashing or no display',
      'PC shutting down during games',
      'BIOS not posting / black screen',
      'PSU fan noise or failure',
      'RAM errors and crashes',
      'Overheating - thermal paste & cooling',
      'Windows game optimisation',
      'Custom PC build and upgrades',
    ],
    metaTitle: 'Gaming PC Repair London | Desktop & Laptop',
    metaDescription: 'Gaming PC and laptop repair across London. GPU, PSU, overheating fixes. Alienware, ASUS ROG, MSI, custom builds. Call 07378 349222.',
    category: 'Windows Laptop & PC',
  },
  {
    slug: 'virus-removal-london',
    title: 'Virus & Malware Removal London',
    shortTitle: 'Virus Removal',
    icon: '🛡️',
    image: '/images/virus-removal-service-unsplash.jpg',
    description: 'Remove viruses, ransomware, spyware and malware from Mac and PC. Same-day service.',
    longDescription: 'Ransomware, spyware, adware and browser hijackers can destroy your data and compromise your privacy. We fully clean your Mac or PC, remove all malware, and set up proper security to prevent reinfection.',
    commonIssues: [
      'Pop-up ads and browser redirects',
      'Ransomware / files encrypted',
      'PC running very slowly',
      'Fake virus warning pop-ups',
      'Webcam or microphone spied on',
      'Suspicious programs starting automatically',
      'Email account hacked via PC',
      'Mac infected with adware',
    ],
    metaTitle: 'Virus Removal London | Malware & Ransomware',
    metaDescription: 'Same-day virus and malware removal across London. Mac and PC. Ransomware, spyware, adware cleaned. No fix, no fee. Call 07378 349222.',
    category: 'Data & Security',
  },
  {
    slug: 'macbook-screen-repair-london',
    title: 'MacBook Screen Repair London',
    shortTitle: 'Screen Repair',
    icon: '🖱️',
    image: '/images/macbook-screen-repair-service-unsplash.jpg',
    description: 'MacBook Pro and MacBook Air screen replacement. Cracked, flickering or dead displays fixed same day.',
    longDescription: 'We replace cracked, flickering, dead, or dim MacBook screens using quality replacement panels. We cover MacBook Pro 13", 14", 15", 16" and MacBook Air 13", 15" - including Retina and Liquid Retina XDR displays.',
    commonIssues: [
      'Cracked MacBook Pro screen',
      'MacBook Air screen broken after drop',
      'Flickering or lines on display',
      'Black screen - backlight failure',
      'MacBook screen damage from liquid',
      'Dim screen - inverter fault',
      'Dead pixels or colour distortion',
      'Screen hinge broken',
    ],
    metaTitle: 'MacBook Screen Repair London | Same Day',
    metaDescription: 'MacBook Pro and MacBook Air screen replacement across London. Cracked, flickering or dead displays. Same-day home visit. Call 07378 349222.',
    category: 'Apple & Mac',
  },
  {
    slug: 'macbook-battery-replacement-london',
    title: 'MacBook Battery Replacement London',
    shortTitle: 'Battery Replacement',
    icon: '🔋',
    image: '/images/zoshua-colah-HEIeRujWthM-unsplash.jpg',
    description: 'MacBook battery not holding charge? We replace MacBook Pro and Air batteries at your door.',
    longDescription: 'A failing MacBook battery drains fast, shuts down unexpectedly or shows "Service Recommended". We replace genuine-spec batteries on all MacBook Pro and MacBook Air models, including glued-in batteries on newer Retina models.',
    commonIssues: [
      'MacBook dies within an hour',
      '"Battery Service Recommended" warning',
      'MacBook only works when plugged in',
      'Battery swollen - urgent safety issue',
      'MacBook shutting off at 20–30%',
      'Cycle count over 1000',
      'MacBook discharging overnight',
      'macOS showing reduced battery capacity',
    ],
    metaTitle: 'MacBook Battery Replacement London',
    metaDescription: 'MacBook Pro and Air battery replacement across London. Home visits, genuine-spec parts. Fast turnaround. No fix, no fee. Call 07378 349222.',
    category: 'Apple & Mac',
  },
  {
    slug: 'water-damage-repair-london',
    title: 'Water Damage Repair London',
    shortTitle: 'Water Damage Repair',
    icon: '💧',
    image: '/images/water-damage-service-unsplash.jpg',
    description: 'MacBook or laptop liquid damage? Act fast - we provide same-day emergency callout.',
    longDescription: 'Spilt water, coffee or juice on your MacBook or laptop? Act immediately - every minute counts with liquid damage. Do not turn it on. Call us now for a same-day emergency visit.',
    commonIssues: [
      'MacBook wet - spilled water or coffee',
      'Keyboard keys not working after spill',
      'MacBook won\'t turn on after liquid damage',
      'Trackpad not responding after water',
      'Laptop screen damaged by liquid',
      'Corrosion on logic board',
      'USB or charging port corroded',
      'Battery short-circuit from water',
    ],
    metaTitle: 'Water Damage Repair London | Mac & Laptop',
    metaDescription: 'Emergency liquid damage repair across London. MacBook and laptop spill recovery. Same-day callout. Do not turn it on - call 07378 349222.',
    category: 'Data & Security',
  },
  {
    slug: 'playstation-repair-london',
    title: 'PlayStation Repair London',
    shortTitle: 'PlayStation Repair',
    icon: '🎮',
    image: '/images/playstation-service-unsplash.jpg',
    description: 'PS5 & PS4 repair at your home. HDMI port, overheating, disc drive & controller faults fixed.',
    longDescription: 'PlayStation not working? We repair PS5 and PS4 consoles at your home or office across Greater London. From the common PS5 HDMI port failure to disc drive faults, overheating shutdowns and controller issues — our engineers diagnose and fix your console on-site, so you are back gaming the same day.',
    commonIssues: [
      'PS5 HDMI port broken — no picture',
      'PS4 / PS5 overheating and shutting down',
      'Disc drive not reading or ejecting discs',
      'PlayStation not turning on',
      'Blue light of death (BLOD)',
      'DualSense / DualShock controller drift',
      'PS5 loud fan noise',
      'PlayStation connected but no display on TV',
      'PSN account issues / system software',
      'USB port broken on controller or console',
    ],
    metaTitle: 'PlayStation Repair London | PS5 & PS4',
    metaDescription: 'PS5 and PS4 repair across Greater London. HDMI port, overheating, disc drive, controller faults fixed at your door. No fix, no fee. Call 07378 349222.',
    category: 'Consoles & Gaming',
  },
  {
    slug: 'gaming-console-repair-london',
    title: 'Gaming Console Repair London',
    shortTitle: 'Console Repair',
    icon: '🕹️',
    image: XBOX_CONSOLE_IMAGE,
    description: 'Xbox, Nintendo Switch and general console repairs at home across Greater London.',
    longDescription: 'We repair gaming consoles including Xbox Series X, Xbox Series S, Xbox One, Nintendo Switch, and other popular systems across Greater London. From HDMI faults and charging issues to overheating and storage problems, we diagnose your console at home or office and explain the fix clearly before any work starts.',
    commonIssues: [
      'Xbox HDMI port damaged or no display',
      'Nintendo Switch not charging',
      'Console overheating and shutting down',
      'Broken USB-C or power ports',
      'Fan noise and dust-related heat issues',
      'Controller pairing or connection faults',
      'Storage errors and corrupt updates',
      'Disc drive or cartridge reader faults',
    ],
    metaTitle: 'Console Repair London | Xbox & Switch',
    metaDescription: 'Gaming console repair across London for Xbox, Nintendo Switch and more. HDMI, charging, overheating, storage and port faults fixed at your door.',
    category: 'Consoles & Gaming',
  },
  {
    slug: 'macbook-pro-repair-london',
    title: 'MacBook Pro Repair London',
    shortTitle: 'MacBook Pro Repair',
    icon: '💻',
    image: '/images/macbook-pro-unsplash.jpg',
    description: 'Specialist MacBook Pro M1, M2, M3 and Intel logic board and screen repair.',
    longDescription: 'We offer hyper-specialised repairs for MacBook Pro 13", 14", 15" and 16" models. Whether you have an older Intel core model with a failing battery, or a brand new M3 Max with a cracked Liquid Retina XDR display, our engineers bring the Apple-certified workshop directly to your home.',
    commonIssues: [
      'M1/M2/M3 MacBook Pro Screen Replacement',
      'MacBook Pro Touch Bar not responding',
      'Logic Board short circuit repair',
      'Battery swollen or Service Recommended',
      'MacBook Pro liquid damage recovery',
      'Overheating and loud fan noise',
    ],
    metaTitle: 'MacBook Pro Repair London | Same Day',
    metaDescription: 'Specialist MacBook Pro repair across London. M1, M2, M3 and Intel models. Screen replacement, battery, liquid damage fixed at your door. No fix, no fee.',
    category: 'Apple & Mac',
  },
  {
    slug: 'macbook-air-repair-london',
    title: 'MacBook Air Repair London',
    shortTitle: 'MacBook Air Repair',
    icon: '💻',
    image: '/images/albert-vinas-F3t-AzyTbyU-unsplash.jpg',
    description: 'Expert MacBook Air repair. M1, M2, M3 and Intel models fixed at your home.',
    longDescription: 'MacBook Air laptops are ultra-thin and highly susceptible to screen cracking and liquid damage. We provide rapid same-day callouts to replace MacBook Air 13" and 15" screens, recover corroded logic boards from coffee spills, and replace exhausted batteries.',
    commonIssues: [
      'MacBook Air M1/M2 screen cracked',
      'Liquid spilled on MacBook Air keyboard',
      'MacBook Air not turning on',
      'Battery draining unusually fast',
      'Trackpad not clicking or responding',
      'USB-C charging ports loose or failing',
    ],
    metaTitle: 'MacBook Air Repair London | Same Day',
    metaDescription: 'Expert MacBook Air repair in London. M1, M2, M3 screen replacement, battery upgrades and liquid damage repair. We come to you. Call 07378 349222.',
    category: 'Apple & Mac',
  },
  {
    slug: 'ps5-hdmi-port-repair-london',
    title: 'PS5 HDMI Port Repair London',
    shortTitle: 'PS5 HDMI Repair',
    icon: '🎮',
    image: '/images/playstation-service-unsplash.jpg',
    description: 'PS5 turning on but no signal? We replace broken PS5 HDMI ports same-day.',
    longDescription: 'The most common PlayStation 5 fault is a broken or loose HDMI port. If your PS5 powers on with a blue or white light but shows "No Signal" on your TV, the port is likely damaged internally. We carry military-grade replacement ports and can micro-solder a brand new HDMI port onto your PS5 motherboard directly at your home.',
    commonIssues: [
      'PS5 No Signal on TV',
      'HDMI port visibly bent or broken',
      'Screen flickering or dropping out',
      'PS5 powers on but black screen',
      'Pins pushed back inside the port',
      'Requires wiggling the cable to get picture',
    ],
    metaTitle: 'PS5 HDMI Port Repair London | Same Day',
    metaDescription: 'PS5 HDMI port repair across London. No signal or broken port? We micro-solder a new HDMI port at your home today. No fix, no fee. Call 07378 349222.',
    category: 'Consoles & Gaming',
  }
];

export function getService(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}
